-- Imported from Airtable CSV snapshot provided by the user on 2026-04-07.
-- Assumptions: use stock real when present, otherwise fall back to stock teorico.
-- Packages are not imported into articulo_componentes in this snapshot because the CSV does not include reliable component quantities.
create temp table _lt_airtable_inventory_import (
  airtable_record_id text not null,
  nombre text not null,
  tipologia text,
  formulario text,
  paquete boolean not null,
  imagen_url text,
  coeficiente numeric(12,4),
  objeto_comun boolean not null,
  minimo_comun boolean not null,
  subgrupo text,
  stock_cp integer not null,
  stock_hu integer not null,
  stock_to integer not null,
  source_name text not null
) on commit drop;
insert into _lt_airtable_inventory_import (
  airtable_record_id, nombre, tipologia, formulario, paquete, imagen_url, coeficiente, objeto_comun, minimo_comun, subgrupo, stock_cp, stock_hu, stock_to, source_name
) values
  ('recQ3SSoHkBtHE5BL', '912 Altitud', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, '912 Altitud'),
  ('recnpue23vHlaLQbD', 'Abridor (PC)', null, null, false, null, null, false, false, 'Puesto Cervezas', 0, 0, 0, 'Abridor (PC)'),
  ('recaOCsbpXYGfV8sX', 'Abridores vino', 'OTROS', 'ARMARIO EVENTO', false, null, null, true, false, 'Caja con Código', 0, 0, 0, 'Abridores vino'),
  ('rec3jrpRgnhdgtRTR', 'Absolut Vodka', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vodka', 0, 0, 0, 'Absolut Vodka'),
  ('recoLlgcKf2kp5sxH', 'Aceitera (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Aceitera (PT)'),
  ('rec3w3ZopMtiaJLWJ', 'Agua grande para trabajadores', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Agua', 0, 0, 0, 'Agua grande para trabajadores'),
  ('recNtCkguziSxcnm5', 'Agua pequeña para clientes', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Agua', 0, 0, 0, 'Agua pequeña para clientes'),
  ('recBTki8hDqbWkL3Y', 'Alargadores (rollo 25m)', 'OTROS', 'EVENTO', false, null, null, true, true, 'EVENTO', 0, 6, 6, 'Alargadores (rollo 25m)'),
  ('recgihQe2EPX50viG', 'Altura (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Altura (PT)'),
  ('recEml2o2fRa2ju9r', 'Ambientador', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Ambientador'),
  ('rec11mX4okdO7LljO', 'Aquabona', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Agua', 0, 0, 0, 'Aquabona'),
  ('recUg7325DAOWIPBj', 'Aquabona con gas', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Agua', 0, 0, 0, 'Aquabona con gas'),
  ('recTpEceA58gJAltM', 'Aquarius limón', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Aquarius limón'),
  ('rect1dskz2UBhwFFO', 'Aquarius naranja', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Aquarius naranja'),
  ('rec9jSmfaZAB9YYjn', 'Arcones de hielo llenos', 'OTROS', 'GENERAL', false, null, null, false, false, 'Hielo', 0, 0, 0, 'Arcones de hielo llenos'),
  ('recOzbDsDABJUMsOO', 'Azúcar (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Endulzantes y Lácteos', 0, 0, 0, 'Azúcar (cajas)'),
  ('recuEONKytV3fPyvx', 'AZUL CLARO - Oasis Pro Glass - Limpiacristales', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'AZUL CLARO - Oasis Pro Glass - Limpiacristales'),
  ('recGUysqpbMXYQPco', 'AZUL OSCURO - Maxx Magic2 - Friega suelos (20L)', 'OTROS', 'EVENTO', false, null, null, false, false, 'Maquinas limpiadoras', 0, 0, 0, 'AZUL OSCURO - Maxx Magic2 - Friega suelos (20L)'),
  ('recSEpem3Gks61q2F', 'Bacardí', 'OTROS', 'MAKRO', false, null, null, false, false, 'Cocteles', 0, 0, 0, 'Bacardí'),
  ('recFniuVcQMZPks9X', 'Baileys', 'OTROS', 'MAKRO', false, null, null, false, false, 'Para Cafés', 0, 0, 0, 'Baileys'),
  ('recJtNZv78RhHmDe2', 'Ballantine''s', 'OTROS', 'MAKRO', false, null, null, false, false, 'Whisky', 0, 0, 0, 'Ballantine''s'),
  ('recDM2GvNjvQ6jSnl', 'Bambú', 'SILLAS', 'ALMACÉN', false, null, 0.03, false, false, 'Sillas', 5, 60, 69, 'Bambú'),
  ('recF5LH0ZbC2jm2zS', 'Bandeja (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Bandeja (PV)'),
  ('recffCmZSz2hCIgdj', 'Bandeja deco cocina (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Bandeja deco cocina (PA)'),
  ('rec0GiW3zVdDF9Su2', 'Bandeja ovalada camareros', 'BANDEJAS', 'GENERAL', false, null, null, false, false, 'EVENTO', 0, 16, 15, 'Bandeja ovalada camareros'),
  ('recmKnokpSdzDpYOP', 'Bandeja redonda camareros', null, 'GENERAL', false, null, null, false, false, 'EVENTO', 41, 15, 11, 'Bandeja redonda camareros'),
  ('rec4nGPz2fdwljt6B', 'Bandeja sushi grande (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Bandeja sushi grande (PS)'),
  ('recj3dHHUuCjnTtt9', 'Bandeja sushi peque (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Bandeja sushi peque (PS)'),
  ('rech2xK628xJOLxUX', 'Barceló', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ron', 0, 0, 0, 'Barceló'),
  ('rec0ahswKvD8oj3lK', 'Barquitos', 'OTROS', 'COCINA', false, null, null, true, true, 'Cocina', 0, 0, 0, 'Barquitos'),
  ('recNcenYbNT7XBKuG', 'Barra de listones de madera', 'BARRAS', 'GENERAL', false, null, null, false, false, 'Útiles Coctel / Fiesta', 1, 4, 5, 'Barra de listones de madera'),
  ('rec5SkGiwKwGFIPW3', 'Barriles Cerveza gastados', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Barriles Cerveza gastados'),
  ('recQxfM0M8p6PI7aO', 'Barriles Cerveza llenos', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Barriles Cerveza llenos'),
  ('recCWvUlAAG0nryAd', 'Base tronco (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Base tronco (PS)'),
  ('recRZjGI0M0OvLIEm', 'Basica_Atril blanco', 'CEREMONIA BASICA', 'GENERAL', false, null, null, false, false, 'Ceremonia', 0, 1, 1, 'Basica_Atril blanco'),
  ('recQo9OBQTJ7OyRv3', 'Basica_Banco blanco', 'CEREMONIA BASICA', 'GENERAL', false, null, null, false, false, 'Ceremonia', 0, 1, 1, 'Basica_Banco blanco'),
  ('recP4eIZazt18zV6E', 'Basica_Consola blanca', 'CEREMONIA BASICA', 'GENERAL', false, null, null, false, false, 'Ceremonia', 0, 1, 1, 'Basica_Consola blanca'),
  ('reclvoMhiLxzpGGk8', 'Baterias fregadoras', 'OTROS', 'LIMPIEZA', false, null, null, true, true, 'Maquinas limpiadoras', 0, 0, 3, 'Baterias fregadoras'),
  ('recorLuXZZGSyYoyN', 'Beefeater', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ginebra', 0, 0, 0, 'Beefeater'),
  ('recpWJvil7DjBEugU', 'Black Label', 'OTROS', 'MAKRO', false, null, null, false, false, 'Whisky', 0, 0, 0, 'Black Label'),
  ('rec8yoLGldAEJmeA7', 'Blanca/Beige', 'SERVILLETAS', 'TELAS', false, null, 0.05, false, false, 'Servilletas', 598, 0, 100, 'Blanca/Beige'),
  ('recauRpmPrHlTNtsX', 'Blancas', null, null, false, null, null, false, false, 'Útiles Coctel / Fiesta', 0, 0, 0, 'Blancas'),
  ('rec9AEg6gYwZhNmkB', 'BN01_Clara Tivoli Antigo', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 6, 10, 14, 'BN01_Clara Tivoli Antigo'),
  ('recGUnsyse4ghTg7w', 'BN02_Oscura Tivoli Moss', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 6, 12, 8, 'BN02_Oscura Tivoli Moss'),
  ('recHNj1QxPw7s3YFP', 'BN03_Hoja Musacea', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 0, 12, 13, 'BN03_Hoja Musacea'),
  ('rec9VEXgfOusipUsb', 'BN04_Clara Strange', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 7, 18, 15, 'BN04_Clara Strange'),
  ('recIpGMSCAUoeC9a4', 'BN05_Kulsan Ottoman Negra', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 0, 31, 15, 'BN05_Kulsan Ottoman Negra'),
  ('recE7RjHaWy0xH3yS', 'BN06_Rectangular Africa', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 2, 21, 12, 'BN06_Rectangular Africa'),
  ('recQLMDjYXUpDByXo', 'BN07_Oval verde Tarantella', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 9, 16, 15, 'BN07_Oval verde Tarantella'),
  ('recigVvTZNHbEtlHN', 'BN08_Rectangular Ming', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 5, 8, 5, 'BN08_Rectangular Ming'),
  ('rec7C5Z9UYwTMlazb', 'BN09_Bayahibe Wood', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 14, 8, 7, 'BN09_Bayahibe Wood'),
  ('recmnLlqawI6CgLLC', 'BN10_Madera de Mango Kaloyan', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 9, 11, 5, 'BN10_Madera de Mango Kaloyan'),
  ('recN6WSsm04vsTgEX', 'BN11_Bowls melamina negro', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 5, 10, 11, 'BN11_Bowls melamina negro'),
  ('recQWX7PWNQ8vgqDJ', 'BN12_Oval Numidia', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 2, 2, 10, 'BN12_Oval Numidia'),
  ('recxe47vWu1oRrFPW', 'BN13_Rectangular Criollo', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 14, 0, 10, 'BN13_Rectangular Criollo'),
  ('reccTyfMY3rAXDiCw', 'BN14_Bowl de madera', 'BANDEJAS', 'ALMACÉN', false, null, null, false, false, 'Bandejas Aperitivos', 0, 4, 4, 'BN14_Bowl de madera'),
  ('recIuLxQNm1SODucQ', 'Bobinas papel cocina', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Bobinas papel cocina'),
  ('recDniCvyfdIe9USr', 'Bol (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Bol (PV)'),
  ('recYrnBxv3ovbb0H2', 'Boligrafos', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Caja con Código', 0, 0, 0, 'Boligrafos'),
  ('recw48mYtL34gAlW9', 'Bolsa Herramientas', null, 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 3', 0, 0, 0, 'Bolsa Herramientas'),
  ('recmPasNyxWRoBV2m', 'Bolsas de basura grandes', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 3', 0, 0, 0, 'Bolsas de basura grandes'),
  ('rec69qzKbDzmSVJvc', 'Bolsas de basura pequeñas', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 3', 0, 0, 0, 'Bolsas de basura pequeñas'),
  ('recCRXbkKAFl9RoC4', 'Bolsas embolsar cubiertos (caja)', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Bolsas embolsar cubiertos (caja)'),
  ('reccfPHq2wgh0mEyT', 'Botellas de butano', 'OTROS', 'COCINA', false, null, null, true, true, 'Cocina', 0, 1, 2, 'Botellas de butano'),
  ('recyaHM7M5Ujn8MIq', 'Botiquin', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Botiquin'),
  ('rechotRnVb2TbHrLK', 'Brugal', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ron', 0, 0, 0, 'Brugal'),
  ('recaIEzTnG4fotBrw', 'Burn', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Burn'),
  ('recvVXqRtjzOWucqK', 'Butaca de mimbre', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 0, 12, 12, 'Butaca de mimbre'),
  ('recOXXRks8F9ga36o', 'Cachaça', 'OTROS', 'MAKRO', false, null, null, false, false, 'Cocteles', 0, 0, 0, 'Cachaça'),
  ('recHTimtGCnqXne0A', 'Café Descafeinado (bolsas 500g)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Cafés', 0, 0, 0, 'Café Descafeinado (bolsas 500g)'),
  ('recjI4oDtasCv36Bo', 'Café Normal (bolsas 1kg)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Cafés', 0, 0, 0, 'Café Normal (bolsas 1kg)'),
  ('recjbEBATkFSLp3uW', 'Caja con Codigo', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Caja con Codigo'),
  ('recz0NpgHWxVFbLn7', 'Caja Grande (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Caja Grande (CB)'),
  ('rec9HySF3v6EYQlUB', 'Caja grande (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Caja grande (PH)'),
  ('recHLzswofmVoF5FC', 'Caja grande y peque (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Caja grande y peque (PA)'),
  ('recft2Tb6LwSBpaW2', 'Caja Imperdibles', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Caja Imperdibles'),
  ('recVhcJa3NjDYz5hZ', 'Caja Madera (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Caja Madera (PC)'),
  ('recJdshwdiztSQAAb', 'Caja palé pequeña', 'OTROS', 'ARMARIO PLANNER', false, null, null, true, true, 'Armario planer(subgrupo momentaneo)', 0, 0, 0, 'Caja palé pequeña'),
  ('recedMSasZToAlfOA', 'Caja pequeña (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Caja pequeña (CB)'),
  ('rec5eIuIta76ytEO3', 'Caja Pequeña (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Caja Pequeña (PH)'),
  ('recY65lSnpTeLM6Hi', 'Caja pequeña (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Caja pequeña (PV)'),
  ('recttMZZIubpvsshK', 'Cajas Medianas (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Cajas Medianas (PV)'),
  ('reco1LYRBZ4tAL3GM', 'Cajon cesta (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Cajon cesta (PT)'),
  ('recY5GOwFO4bNn9nd', 'Cajones madera (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Cajones madera (PT)'),
  ('recI29oOYpc8T86E4', 'Caña vegetal', 'BAJOPLATO', 'ALMACÉN', false, 'https://v5.airtableusercontent.com/v3/u/52/52/1775592000000/cDXgfPOOBY7WeI9OZsaIKg/i8CVsJbgqhl2_vpAzluvpDEvkNquxtZyY4AcWCry433cOGNvF9wqXr9s1JUEb8zjoEMR0yOqsN0T7KZGemUb3gDZ071TAKi6ue3p4niwW5rjmIpe0FM8f7lTMXUn04Ip5vvTl3UZFTyTAKZoGFzwOkO1HblBtStx1LrVlqd8PHkzLWWra3QihWuqiX48QM-j2IxKftJzi8Pa9iGAODlX_w/zL-KuJ3ueX2mZhHQWNTUjsHCI-el4SYsiHVhX4Biujo', 0.05, false, false, 'Bajoplato', 212, 160, 20, 'Caña vegetal'),
  ('rec23HLzBf8uBz6nm', 'Cápsulas Descafeinado (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Cafés', 0, 0, 0, 'Cápsulas Descafeinado (cajas)'),
  ('recW9GUdqei23b8AU', 'Cápsulas Normal (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Cafés', 0, 0, 0, 'Cápsulas Normal (cajas)'),
  ('recKLy0fcGwphWrkE', 'Cara buda (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Cara buda (PS)'),
  ('recqKDmI9dDhhnQb8', 'Cargadores baterías', 'OTROS', 'LIMPIEZA', false, null, null, true, true, 'Maquinas limpiadoras', 0, 0, 2, 'Cargadores baterías'),
  ('recn7RfOzb7lOHf20', 'Carlota Suria', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Cava', 0, 0, 0, 'Carlota Suria'),
  ('rectn2qdG9rsn19os', 'Carretilla (PC)', null, null, false, null, null, false, false, 'Puesto Cervezas', 0, 0, 0, 'Carretilla (PC)'),
  ('recyQ6y2fZV8d3sNz', 'Carteles impresos', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Carteles impresos'),
  ('rechE0l7CGnqLODon', 'Cartulina/Folios A4', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Cartulina/Folios A4'),
  ('recNXUZJJV7bAnsRj', 'Cassalla Cerveró', 'OTROS', 'MAKRO', false, null, null, false, false, 'Chupitos', 0, 0, 0, 'Cassalla Cerveró'),
  ('rectv3jKXsxOqwrpv', 'Cebralin', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Cebralin'),
  ('recysJ4JeOufP4I3H', 'Celler Vell', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Cava', 0, 0, 0, 'Celler Vell'),
  ('rech6b5C8s8JO36XE', 'Celo', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Celo'),
  ('recXCluJp3fOHcYQc', 'Ceniceros', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Útiles Coctel / Fiesta', 22, 12, 12, 'Ceniceros'),
  ('recqTE1xUfj19Gdnl', 'Ceniceros de pie', 'OTROS', 'EVENTO', false, null, null, true, true, 'EVENTO', 0, 2, 2, 'Ceniceros de pie'),
  ('recCNYep1w9P9ITKU', 'Cepillo', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Cepillo'),
  ('recANqGONsWzOJBuE', 'Cera', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Cera'),
  ('recdZLvNvu4KHEgO5', 'Cerveza Con Limón', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Cerveza Con Limón'),
  ('rectC34NHYIHNEJ55', 'Cerveza Sin Alcohol', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Cerveza Sin Alcohol'),
  ('rec9Ccnec2nhu4WTX', 'Cerveza Sin Gluten', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Cerveza Sin Gluten'),
  ('recfqCcxgvPr7DU1i', 'Cesta', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Cesta'),
  ('recVNbOCeL1Uo8AvI', 'Cesta caña vegetal', 'PLATO PAN', 'ALMACÉN', false, null, 0.05, false, false, 'Plato pan', 140, 160, 0, 'Cesta caña vegetal'),
  ('recbOKRsdfSOlTWpP', 'Cesta gallina rojo (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Cesta gallina rojo (PT)'),
  ('rec9icYY9rT7wojtE', 'Cesta mimbre (nº perchas)', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Cesta mimbre (nº perchas)'),
  ('rec293RB5gE9nJJhj', 'Cesta Minbre (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Cesta Minbre (PH)'),
  ('rec4Th6xIY1cekUYq', 'Cesta Minbre (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Cesta Minbre (PS)'),
  ('rec5EBxb6Wn5zZYef', 'Cesta Negra (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Cesta Negra (PT)'),
  ('recTWRpbyMJnejBvx', 'Cestas con rama oscura (PJ)', null, null, false, null, null, false, false, 'Puesto Jamón', 0, 0, 0, 'Cestas con rama oscura (PJ)'),
  ('reciu849KkzsZ9B6B', 'Cestas mimbre', 'OTROS', 'ARMARIO PLANNER', false, null, null, true, true, 'Armario planer(subgrupo momentaneo)', 0, 0, 0, 'Cestas mimbre'),
  ('rec1ldpmW41X6mHUm', 'Cestita minbre (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Cestita minbre (PT)'),
  ('recFVsOFfRiVMI1Sq', 'Cesto arroz (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Cesto arroz (PA)'),
  ('recrx9XNqqXlXSRoI', 'Cestos (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Cestos (PT)'),
  ('recqzpHrerMBgoF8d', 'Champagneras', 'OTROS', 'EVENTO', false, null, null, true, true, 'EVENTO', 0, 6, 7, 'Champagneras'),
  ('recesqWbjz0h7pX0m', 'Chicles', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Chicles'),
  ('rectsHiF7LMcM9DOR', 'Choza crianza', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Tinto', 0, 0, 0, 'Choza crianza'),
  ('recOHwzrocyJdpzIS', 'Ciento Volando blanco', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Ciento Volando blanco'),
  ('recIxelnnDaEbNtjA', 'Ciento Volando rojo', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Ciento Volando rojo'),
  ('reca4hzkYAJEp755D', 'Cinta adhesiva (transparente)', 'OTROS', 'ARMARIO PLANNER', false, null, null, true, true, 'Armario planer(subgrupo momentaneo)', 0, 0, 0, 'Cinta adhesiva (transparente)'),
  ('recaYQc7isTSOzN7G', 'Cinta Americana (negra)', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Cinta Americana (negra)'),
  ('recjNi8hLg71eRLkd', 'Cinta embolsar cubiertos', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Cinta embolsar cubiertos'),
  ('reccea2Si5pvYeaCI', 'Cinzano blanco', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Cinzano blanco'),
  ('recAMCCMzeq6Mz8gW', 'Cinzano rojo', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Cinzano rojo'),
  ('recSNuKTHiiA5fxSV', 'Coca-Cola', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Coca-Cola'),
  ('rec2Ps77Zwl0aT9QE', 'Coca-Cola Zero', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Coca-Cola Zero'),
  ('rec1N7X3EEygWFmZM', 'Cocteleras (PM)', null, null, false, null, null, false, false, 'Puesto Mojitos', 0, 0, 0, 'Cocteleras (PM)'),
  ('recBQtHhFLzRrwjgW', 'Cointreau', 'OTROS', 'MAKRO', false, null, null, false, false, 'Cocteles', 0, 0, 0, 'Cointreau'),
  ('reczI4dJeoRHx47ST', 'Colonia', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Colonia'),
  ('rec5OWiPi7ptBm97Q', 'Compresas', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Compresas'),
  ('rec4FSNPdHc1pG8BU', 'Copa de sorbete', 'CRISTALERIA', 'ALMACÉN', false, 'https://v5.airtableusercontent.com/v3/u/52/52/1775592000000/L71-IA5BFcZt1Rkdn1WHjg/_LTRRFXwDJG5tuEUUv1bmI8jU20R9hlHnGDfikHZyTCvP26kFeepRAOxUbCU0ZV0iOtt26JlbQm7ZXax2HFJn_Luw5mvJERyaDAG1iO2OfkPnCYlJdCxKu_FLAVdoIplhaJ2DiJxI1pfiCoXqGq08MmsrAzHhqdrrEx32BHAoIMD0tEnR-dyhPcj73hU5cwuF-Cp8PTmU6bMUjCMqKgh3Q/w-kNSedDjo0qygEgztBrsdZ3Wh1FJXNnh74fgnumpXk', 0.06, false, false, 'Copas Vino / Cava', 144, 473, 0, 'Copa de sorbete'),
  ('rec0h4Dxvevqh8EoK', 'Copa Julieta transparente', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas / Vasos Agua', 254, 0, 123, 'Copa Julieta transparente'),
  ('recTcl5WSbrzRf6in', 'Copa para coctel', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas Vino / Cava', 620, 753, 769, 'Copa para coctel'),
  ('rectC4cxy0pS5JGmE', 'Copa Verona Ambar', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas / Vasos Agua', 0, 176, 200, 'Copa Verona Ambar'),
  ('reccPG1pLnOCDEqZc', 'Cristal SOL', 'BAJOPLATO', 'ALMACÉN', false, 'https://v5.airtableusercontent.com/v3/u/52/52/1775592000000/_Xj6uF_1wn5x_HG8V7vcVw/da5z9QBqa_kxX9rWm1coPEeZk4r5zpVisiNLZupe5-uOV_yO9lt9xY6UB2HPICU2GyaGh6pJVctk2oGehktrsUHYhaoo0svWvXDfGbNdxHe9v42osb9n_qVqge0QTszfSm2LZYHKUL-GeZ0nsusNCGGN5tjWrTI8dQFivlVH3Ng/gVpT2KX2exPHTQC9CkXFEDbpjFcyg-6o7ijCRqLCTdg', 0.06, false, false, 'Bajoplato', 166, 140, 160, 'Cristal SOL'),
  ('recpObEWAFAW8HrlD', 'Cristal sol', 'PLATO PAN', 'ALMACÉN', false, null, 0.06, false, false, 'Plato pan', 190, 144, 180, 'Cristal sol'),
  ('recRUybHbuJYStyFy', 'Crossback', 'SILLAS', null, false, null, 0.03, false, false, 'Sillas', 63, 0, 179, 'Crossback'),
  ('reccT8iGu8KXh4fd0', 'Cuadrado niños 30cm', 'PLATOS', 'ALMACÉN', false, null, 0.06, false, false, 'Platos', 2, 15, 15, 'Cuadrado niños 30cm'),
  ('recJBhDLjIGg0HsWF', 'Cuadro vermut (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Cuadro vermut (PV)'),
  ('recAv6UydFTQO6ejU', 'Cuberteros (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Cuberteros (PT)'),
  ('rec8gVJxnMrQgWYiV', 'Cubitera grande (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 9, 9, 'Cubitera grande (PV)'),
  ('recLok7qm3AuUpkBt', 'Cubo (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Cubo (PV)'),
  ('recy7wx4Cx1FHfFzK', 'Cubo negro setas coctel', 'OTROS', 'EVENTO', false, null, null, true, true, 'Útiles Coctel / Fiesta', 0, 9, 0, 'Cubo negro setas coctel'),
  ('recR5ACezS9h23i7v', 'Cubo plastico (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Cubo plastico (PV)'),
  ('recpaZ8Legu25BA2s', 'Cubos basura cóctel', 'OTROS', 'LIMPIEZA', false, null, null, false, false, 'Útiles Coctel / Fiesta', 0, 0, 0, 'Cubos basura cóctel'),
  ('rec8eD6hmRQAyrhfr', 'Cubos basura grandes', 'OTROS', 'LIMPIEZA', false, null, null, false, false, 'EVENTO', 0, 0, 0, 'Cubos basura grandes'),
  ('rec9t5BB00v7789qc', 'Cubos mocho', 'OTROS', 'LIMPIEZA', false, null, null, true, true, 'Utensilios limpieza', 0, 0, 2, 'Cubos mocho'),
  ('recmDofiiJ16cSHhO', 'Cuchara café', 'CAFÉ/TE', null, false, null, -0.3, false, false, 'Para Cafés', 0, 0, 0, 'Cuchara café'),
  ('recIvYWAxuMr1Aoki', 'Cucharas mezcladoras de coctel (PM)', null, null, false, null, null, false, false, 'Puesto Mojitos', 0, 0, 0, 'Cucharas mezcladoras de coctel (PM)'),
  ('recod4qzQZyyAnHq8', 'Cucharon (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Cucharon (PV)'),
  ('recAYsfOUd5dgMddB', 'Cuchillo untar (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Cuchillo untar (PQ)'),
  ('recUERuUaUfjkP0Qj', 'Cuencos (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Cuencos (PS)'),
  ('recbHpT73ix0mt7oM', 'Cuencos barro (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Cuencos barro (PA)'),
  ('recLDhNkYXyCVgvRc', 'Cuerda', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Cuerda'),
  ('recqjEXVb7QVlidZ8', 'Cullerot', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Cullerot'),
  ('reckhYQAogqctLqgb', 'Cutty Sark', 'OTROS', 'MAKRO', false, null, null, false, false, 'Whisky', 0, 0, 0, 'Cutty Sark'),
  ('recofFpxQFmuqGVbP', 'Delantal granate cocina', 'MANTEL', 'TELAS', false, null, null, false, false, 'EVENTO', 10, 0, 0, 'Delantal granate cocina'),
  ('recjjYrkTK5RifSBw', 'Delantal marrón servicio', 'MANTEL', 'TELAS', false, null, null, false, false, 'EVENTO', 20, 18, 16, 'Delantal marrón servicio'),
  ('rec8tkKFpfYmovb9e', 'Desodorante', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 3, 'Desodorante'),
  ('recLW9RVI2F5T69RP', 'Dorada_Cuchara postre', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 780, 0, 0, 'Dorada_Cuchara postre'),
  ('recw7hvRIaruqWw2m', 'Dorada_Cucharita café', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 534, 0, 0, 'Dorada_Cucharita café'),
  ('rec7VdnupMdTCK5sZ', 'Dorada_Cuchillo punta', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 500, 0, 0, 'Dorada_Cuchillo punta'),
  ('recLf6fzEaawSli0c', 'Dorada_Cuchillo redondo', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 570, 0, 0, 'Dorada_Cuchillo redondo'),
  ('recuYh7Lm1ZuzjYcK', 'Dorada_Tenedor postre', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 527, 0, 0, 'Dorada_Tenedor postre'),
  ('recwsRoFzdGzwYXDv', 'Dorada_Tenedor trinchero', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 1734, 0, 0, 'Dorada_Tenedor trinchero'),
  ('recFeZE7ARz2jbJH8', 'Dorado', 'MANTEL', 'TELAS', false, null, 0.11, false, false, 'Manteles', 40, 14, 0, 'Dorado'),
  ('rec00CIVVQyZvMLjN', 'Encendedores largos', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Encendedores largos'),
  ('rec7icoykdXeofeGN', 'Enjuague bucal', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Enjuague bucal'),
  ('recaCaYDz3Kr695wb', 'Escoba', 'OTROS', 'LIMPIEZA', false, null, null, true, true, 'Utensilios limpieza', 0, 0, 5, 'Escoba'),
  ('recrzlCCHBW0ZMJfm', 'Escobilla del váter (reserva)', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Escobilla del váter (reserva)'),
  ('rech4tQBjyxELV91T', 'Escobón', 'OTROS', 'LIMPIEZA', false, null, null, true, true, 'Utensilios limpieza', 0, 0, 2, 'Escobón'),
  ('recn6BG4o6vfseUeF', 'Estrella Damm', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Estrella Damm'),
  ('recgnLn66NOpTooBm', 'Estrella Galicia', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Estrella Galicia'),
  ('recztEGakQSym1ELY', 'Estrella Levante', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Estrella Levante'),
  ('recfivYcokQ94qpbO', 'Estropajos', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 3', 0, 0, 0, 'Estropajos'),
  ('recl4VmOmkoAaqylw', 'Estructura altura mesa (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Estructura altura mesa (CB)'),
  ('recW6mHLQQRVjUDci', 'Evento general', null, null, false, null, null, false, false, null, 0, 0, 0, 'Evento general'),
  ('rec7REDkuhaD4dKIp', 'Fanta limón', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Fanta limón'),
  ('recVwzSp4PZCo5h3y', 'Fanta naranja', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Fanta naranja'),
  ('recBPmiRkFnJiZAOY', 'Farolillo con 2 ramas (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Farolillo con 2 ramas (PT)'),
  ('rec0yilUQEwZz2HF7', 'Farolillo Minbre (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Farolillo Minbre (PS)'),
  ('recQoqmJP3glUF2b5', 'Farolillo negro (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Farolillo negro (PS)'),
  ('recwEg5vcf0Du32ui', 'Figura buda (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Figura buda (PS)'),
  ('recf1PabBVLxBrFLU', 'Filo dorado', 'PLATO PAN', 'ALMACÉN', false, null, 0.06, false, false, 'Plato pan', 240, 0, 145, 'Filo dorado'),
  ('recBHvco9bgNTword', 'Finca Das Antas', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Finca Das Antas'),
  ('recGmgkeIzrMGfNGT', 'Finca El Pla blanco', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Finca El Pla blanco'),
  ('recU7Vo20cJc0OmIe', 'Finca El Pla tinto', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Tinto', 0, 0, 0, 'Finca El Pla tinto'),
  ('recWJmdghoPOJwuvm', 'Focos de luz extra', 'OTROS', 'EVENTO', false, null, null, true, true, 'EVENTO', 0, 0, 0, 'Focos de luz extra'),
  ('rec3Nd3cTN06KReuW', 'Fregadoras', 'OTROS', 'LIMPIEZA', false, null, null, true, true, 'Maquinas limpiadoras', 0, 0, 3, 'Fregadoras'),
  ('recj4qXJjSxTTMlrc', 'Fundas de Neveras', 'NEVERAS', 'EVENTO', false, null, null, false, false, 'EVENTO', 2, 2, 4, 'Fundas de Neveras'),
  ('recOflFTOjQYwkv9b', 'Fuzetea', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Fuzetea'),
  ('recFsE7OjXUGHolBA', 'Gallina con paja (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Gallina con paja (PH)'),
  ('recxCdK75ywbCR6S1', 'Gas Tirador lleno', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Gas Tirador lleno'),
  ('recrMtxGL3m8ACe97', 'Gas Tirador vacío', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Gas Tirador vacío'),
  ('reckkbtCO5Ss2VEUO', 'Generadores', 'OTROS', 'EVENTO', false, null, null, true, true, 'EVENTO', 0, 0, 0, 'Generadores'),
  ('recqxlvVIKXuSQUox', 'Gomas de pelo', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Gomas de pelo'),
  ('reccazvs0BJYTFJeS', 'Gomina', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Gomina'),
  ('rec89D8gCnPsxSX5f', 'Gris perla', 'MANTEL', 'TELAS', false, null, -1.11, false, false, 'Manteles', 36, 9, 10, 'Gris perla'),
  ('rec0rd5yNDq4G6NqF', 'Guantes talla L', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Guantes talla L'),
  ('rect4ZBh8YnGxytTw', 'Guantes talla M', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Guantes talla M'),
  ('recGevkFoJgMsntIP', 'Hilo dental', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Hilo dental'),
  ('recAQR0BQdAPZkFY2', 'Horquillas', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Horquillas'),
  ('recgvjRaULClislqk', 'Huevera (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Huevera (PH)'),
  ('rec2mcAe5zEKAacUj', 'Hueveras (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Hueveras (PT)'),
  ('recNa9wuUcgTqtvpm', 'Indicador buffet (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Indicador buffet (PH)'),
  ('recBJNEuMvvXbnjTE', 'Indicador Buffet (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Indicador Buffet (PQ)'),
  ('rec0WM7NQ4tye90IK', 'Indicador Maceta alargada (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Indicador Maceta alargada (PA)'),
  ('recAjgW9OWTkwtUYk', 'Inox_Cuchara postre', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 268, 150, 195, 'Inox_Cuchara postre'),
  ('recs4IEDTqqcEVEqg', 'Inox_Cuchara sopera', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 151, 0, 0, 'Inox_Cuchara sopera'),
  ('reciXd1XsA8QaHZEc', 'Inox_Cucharita café', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 5, 150, 195, 'Inox_Cucharita café'),
  ('rec96r5YnSiJK1FnL', 'Inox_Cuchillo punta', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 126, 150, 195, 'Inox_Cuchillo punta'),
  ('recgu1jWI96iqIQJN', 'Inox_Cuchillo redondo', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 256, 0, 0, 'Inox_Cuchillo redondo'),
  ('recvZeAeaxdu1YaHo', 'Inox_Tenedor postre', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 101, 150, 195, 'Inox_Tenedor postre'),
  ('recuqOY7wxOLvurnh', 'Inox_Tenedor trinchero', 'CUBERTERIA', 'ALMACÉN', false, null, 0.05, false, false, 'Cubertería', 478, 280, 195, 'Inox_Tenedor trinchero'),
  ('recVbMOYNW6L23ubZ', 'Insecticida', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Insecticida'),
  ('rec9FT4UR4ztSQrm7', 'J&B', 'OTROS', 'MAKRO', false, null, null, false, false, 'Whisky', 0, 0, 0, 'J&B'),
  ('recB67kAjFInKDPqW', 'Jagger', 'OTROS', 'MAKRO', false, null, null, false, false, 'Chupitos', 0, 0, 0, 'Jagger'),
  ('recbfvViMOSXR1qr9', 'Jarra de limonada', 'JARRA', 'ALMACÉN', false, null, null, false, false, 'Ceremonia', 27, 15, 11, 'Jarra de limonada'),
  ('recFiyYiVKZ49pjow', 'Jarras Metalicas (PM)', null, null, false, null, null, false, false, 'Puesto Mojitos', 0, 0, 0, 'Jarras Metalicas (PM)'),
  ('rec7bTKLPAniuuiui', 'Jarron blanco lavanda (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Jarron blanco lavanda (PT)'),
  ('recvqFx4Wuy9SpM0J', 'Jarron minbre (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Jarron minbre (PT)'),
  ('recyMbXkhY0fjcINF', 'Jarroncitos difs tamaños (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Jarroncitos difs tamaños (PA)'),
  ('recSWQ2xEs6ceInsx', 'Jose Cuervo', 'OTROS', 'MAKRO', false, null, null, false, false, 'Chupitos', 0, 0, 0, 'Jose Cuervo'),
  ('recSV2QZaBpDRhdqK', 'Kit antiquemaduras', 'OTROS', 'ARMARIO EVENTO', false, null, null, true, true, 'Cocina', 0, 0, 0, 'Kit antiquemaduras'),
  ('recemMTF0RvitLBnu', 'Kit contra atragantamiento', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Kit contra atragantamiento'),
  ('rec8wtX1AXdf24pB2', 'Kit de costura', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Kit de costura'),
  ('recsU1dpOEJYqmyd2', 'Kleenex Gel en Espuma', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Kleenex Gel en Espuma'),
  ('recheRoR1hyyFqHql', 'Laca', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Laca'),
  ('recZyS7FPHYH1nqEP', 'Lamina tronco (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Lamina tronco (PQ)'),
  ('reckii0iGH1Z7RxmQ', 'Larios 12', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ginebra', 0, 0, 0, 'Larios 12'),
  ('rec2SL9rwNhf14Pv1', 'Leche Condensada (botellas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Endulzantes y Lácteos', 0, 0, 0, 'Leche Condensada (botellas)'),
  ('rectKaOioEtM3W2ij', 'Leche Condensada (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Endulzantes y Lácteos', 0, 0, 0, 'Leche Condensada (cajas)'),
  ('recrY0xPFGFp1tY2a', 'Leche Normal (brick)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Endulzantes y Lácteos', 0, 0, 0, 'Leche Normal (brick)'),
  ('recBAD9AfnsAvrDek', 'Leche sin Lactosa (brick)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Endulzantes y Lácteos', 0, 0, 0, 'Leche sin Lactosa (brick)'),
  ('recONZCFUOLlpWt9Q', 'Lejia', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Lejia'),
  ('recBgM9n7BEqA24Wf', 'Licor 43', 'OTROS', 'MAKRO', false, null, null, false, false, 'Para Cafés', 0, 0, 0, 'Licor 43'),
  ('recieBiH1JQBfIXJi', 'Limas de uñas', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Limas de uñas'),
  ('recJkq7g0GGrWw073', 'Limoncello', 'OTROS', 'MAKRO', false, null, null, false, false, 'Para Cafés', 0, 0, 0, 'Limoncello'),
  ('recADEj5x4zr6Wkps', 'Lisa_Copa Blanco', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas Vino / Cava', 348, 63, 32, 'Lisa_Copa Blanco'),
  ('recWbNIfcWzqB3Ek0', 'Lisa_Copa Cava', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas Vino / Cava', 144, 473, 0, 'Lisa_Copa Cava'),
  ('recRce6DjTETmZ1r3', 'Lisa_Copa Cava Ancha', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas Vino / Cava', 40, 0, 0, 'Lisa_Copa Cava Ancha'),
  ('recsR3wJzKhJZGVJh', 'Lisa_Copa Tinto', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas Vino / Cava', 331, 212, 0, 'Lisa_Copa Tinto'),
  ('recJtbG715BNbniAI', 'Llave mecanismo baños (cajita gris)', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Llave mecanismo baños (cajita gris)'),
  ('recrvrNmTVVrghdnG', 'Llave mecanismo baños (reserva)', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Caja con Código', 0, 0, 0, 'Llave mecanismo baños (reserva)'),
  ('recGZ2dcDuVPPWQK4', 'Los Frailes', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Tinto', 0, 0, 0, 'Los Frailes'),
  ('recnKnsoC2UDkg1Al', 'Maceta (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Maceta (PQ)'),
  ('reczqs4kId7Jo9eK9', 'Maceta Alargada (PJ)', null, null, false, null, null, false, false, 'Puesto Jamón', 0, 0, 0, 'Maceta Alargada (PJ)'),
  ('rectscCS6NNDNicqh', 'Maceta Grande (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Maceta Grande (PQ)'),
  ('reccqL1YfEbvCIpnT', 'Maceta peque (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Maceta peque (PQ)'),
  ('reccjvI5U6fT4zaos', 'Maceta pequeña (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Maceta pequeña (PH)'),
  ('rec3b1W1Vxl1lZxJe', 'Maceta rafia (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Maceta rafia (PV)'),
  ('recQXY6zmHJ7OfkXW', 'Maceta rafia alargada (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Maceta rafia alargada (PC)'),
  ('recp37RqCG2UXGTKh', 'Maceta rafia con rama (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Maceta rafia con rama (PC)'),
  ('rec2OgZgZFxh4EfQi', 'Maceta Rectangular (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Maceta Rectangular (PH)'),
  ('recrTQBYaO1jjomHg', 'Maceta redonda (PJ)', null, null, false, null, null, false, false, 'Puesto Jamón', 0, 0, 0, 'Maceta redonda (PJ)'),
  ('recx62478zUbtiwnT', 'Macetal (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Macetal (PQ)'),
  ('recn5sDXwRDpXoU8E', 'Macetas (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Macetas (PS)'),
  ('recnKnwtdWW1xPznM', 'Macetas Redondas (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Macetas Redondas (PC)'),
  ('rec6yX3mBE5SFjwz7', 'Mala vida', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Tinto', 0, 0, 0, 'Mala vida'),
  ('recALmPiFXnckRa79', 'Mantel blanco gueridones', 'MANTEL', 'TELAS', false, null, 0.11, false, false, 'Manteles', 17, 4, 5, 'Mantel blanco gueridones'),
  ('recLrNRV6ODU4Tzre', 'Mantel vinchy amarillo (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Mantel vinchy amarillo (PC)'),
  ('recBZgqZcXInVeuIf', 'Mantel vinchy rojo (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Mantel vinchy rojo (PT)'),
  ('rec3kAIg7qX8FlPzO', 'Manzanilla (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Infusiones', 0, 0, 0, 'Manzanilla (cajas)'),
  ('rec8x9nli5S99k56A', 'Maquina embolsar cubiertos', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Maquina embolsar cubiertos'),
  ('reci9oi0kjXWpYXk5', 'Marie Brizard', 'OTROS', 'MAKRO', false, null, null, false, false, 'Para Cafés', 0, 0, 0, 'Marie Brizard'),
  ('rec7GP445cixzGT7a', 'MARRON - Greaselift - Desengrasante', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'MARRON - Greaselift - Desengrasante'),
  ('recYw7L68xcSwMOmh', 'Martin Codax', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Martin Codax'),
  ('recl1FiBQsI4tg142', 'Martini Blanco', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Martini Blanco'),
  ('recLlFQfAGhBgh5Bf', 'Martini Rosso', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Martini Rosso'),
  ('recymmoC5A0abx0fM', 'Master''s', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ginebra', 0, 0, 0, 'Master''s'),
  ('recBoMt5TPma7e4Q1', 'Medallón natural', null, null, false, null, null, false, false, 'Sillas', 99, 244, 135, 'Medallón natural'),
  ('recl4CqRacZbFLOvy', 'Mesa Candy Bar', 'MESA', 'GENERAL', false, null, null, false, false, 'Útiles Coctel / Fiesta', 0, 1, 1, 'Mesa Candy Bar'),
  ('recqr3Sl83jB8zP2q', 'Mesero (PT)', null, null, false, null, null, false, false, 'Puesto Tortillas', 0, 0, 0, 'Mesero (PT)'),
  ('rec1dc3qaev59ExpX', 'Meseros', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 3', 0, 0, 0, 'Meseros'),
  ('recb7hm7N2fVGxbd0', 'Mistela', 'OTROS', 'MAKRO', false, null, null, false, false, 'Para Cafés', 0, 0, 0, 'Mistela'),
  ('recYhBh8cn52neJRB', 'Mochos', 'OTROS', 'LIMPIEZA', false, null, null, true, true, 'Utensilios limpieza', 0, 0, 1, 'Mochos'),
  ('recpx6cC9eRQIukDT', 'MORADO - Kitchen Pro - Desinfectante', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'MORADO - Kitchen Pro - Desinfectante'),
  ('recKXCpwCxLWYabsY', 'Mortero de coctel (PM)', null, null, false, null, null, false, false, 'Puesto Mojitos', 0, 0, 0, 'Mortero de coctel (PM)'),
  ('recWlPCfmiMhhf4Hh', 'Mortero difs tamaños (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Mortero difs tamaños (PA)'),
  ('recQfaygaYTnm3dBX', 'Moskovskaya', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vodka', 0, 0, 0, 'Moskovskaya'),
  ('recJohLIUM3qLpLdY', 'Mostaza', 'SERVILLETAS', 'TELAS', false, null, 0.05, false, false, 'Servilletas', 336, 175, 0, 'Mostaza'),
  ('recTXOnM14Qwg9jb1', 'Nanas', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 3', 0, 0, 0, 'Nanas'),
  ('reckIZEfBfOfeo811', 'Nasol', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Cava', 0, 0, 0, 'Nasol'),
  ('recGGHTK5lnpusfrx', 'Naxus Tempranillo', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Tinto', 0, 0, 0, 'Naxus Tempranillo'),
  ('recPJBk9o4F95luh8', 'Naxus verdejo', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Naxus verdejo'),
  ('recXGhQLc2q7oeKcv', 'Negro', null, null, false, null, null, false, false, 'EVENTO', 71, 15, 25, 'Negro'),
  ('rec5Ihwe5VuWC6Xww', 'Neveras', 'NEVERAS', 'EVENTO', false, null, null, false, false, 'EVENTO', 0, 8, 13, 'Neveras'),
  ('recbOF4E3uYDXTIFP', 'Nodus Sauvignon blanco', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Nodus Sauvignon blanco'),
  ('recPmA3z94aTpcV2k', 'Pajitas', 'OTROS', 'COCINA', false, null, null, true, true, 'Cocina', 0, 0, 40, 'Pajitas'),
  ('rec5hLGw5UQ3MBDll', 'Papel secamanos', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 3', 0, 0, 0, 'Papel secamanos'),
  ('reccb9KxH7z465ZNj', 'Paragüas', 'OTROS', 'GUARDARROPA', false, null, null, true, true, 'EVENTO', 0, 6, 10, 'Paragüas'),
  ('recTUm4dAuINqYOmr', 'Peine', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Peine'),
  ('rec64o7UGUzrj6m5R', 'Peramor', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Peramor'),
  ('recKqYRp3YHTBbgyq', 'Perchas', null, null, false, null, null, false, false, 'EVENTO', 0, 0, 0, 'Perchas'),
  ('recTGi70D3A29ZVTh', 'Permanentes blanco y negro', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Permanentes blanco y negro'),
  ('rec9xEhGuXfd64Qhe', 'Piedra | Manteles', 'MANTEL', 'TELAS', false, null, -1.11, false, false, 'Manteles', 41, 0, 0, 'Piedra'),
  ('recReAiBifdxB4L9O', 'Piedra | Servilletas', 'SERVILLETAS', 'TELAS', false, null, 0.05, false, false, 'Servilletas', 275, 0, 0, 'Piedra'),
  ('recTLUEnxaE0I83jG', 'Pies de Sombrillas', 'SOMBRILLAS', 'GENERAL', false, null, null, false, true, 'Útiles Coctel / Fiesta', 0, 15, 10, 'Pies de Sombrillas'),
  ('recm2BhUelH31P6Ah', 'Pinganillos', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 3', 0, 13, 8, 'Pinganillos'),
  ('recFOvmUV1XK8Ql1R', 'Pinzas (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Pinzas (PV)'),
  ('recuSIJ6e9uJx9u6e', 'Pinzas apoyo camareros', null, 'EVENTO', false, null, null, true, true, 'EVENTO', 0, 20, 21, 'Pinzas apoyo camareros'),
  ('recWEBHYP6HbSTGEL', 'Pinzas de hielo metalicas (PM)', null, null, false, null, null, false, false, 'Puesto Mojitos', 0, 0, 0, 'Pinzas de hielo metalicas (PM)'),
  ('reccYoynQtrKdnzBk', 'Pinzas dentadas metálicas (PM)', null, null, false, null, null, false, false, 'Puesto Mojitos', 0, 0, 0, 'Pinzas dentadas metálicas (PM)'),
  ('recL93bjAK4xYpF6Y', 'Pinzas hielo', 'OTROS', 'COCINA', false, null, null, true, true, 'EVENTO', 0, 12, 9, 'Pinzas hielo'),
  ('reciq1AWBo9mOIGDp', 'Pinzas Madera (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Pinzas Madera (PC)'),
  ('recb1OqFvbdwnCxUV', 'Pinzas madera (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Pinzas madera (PS)'),
  ('recd7GsWVjgxkr6II', 'Pinzas pequeñas madera', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Pinzas pequeñas madera'),
  ('rec5II5I8fUSkfK1m', 'Pizaras (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Pizaras (PC)'),
  ('recnKhKZKn6j4S4Bt', 'Pizarra (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Pizarra (PS)'),
  ('rec0zKwVr6HpqQqCk', 'PL01_Sphere Natural Clear 25cm', 'PLATOS', 'ALMACÉN', false, null, 0.06, false, false, 'Platos', 178, 216, 192, 'PL01_Sphere Natural Clear 25cm'),
  ('recBCYHj9SmDqOpWd', 'PL02_Linneo 27cm', 'PLATOS', 'ALMACÉN', false, null, 0.06, false, false, 'Platos', 5, 304, 121, 'PL02_Linneo 27cm'),
  ('rec3AnKVo58tysLCy', 'PL03_Sopero ovalado', 'PLATOS', 'ALMACÉN', false, null, 0.06, false, false, 'Platos', 3, 264, 177, 'PL03_Sopero ovalado'),
  ('reccGIceU6Tajk6NY', 'PL04_Llano Gourmet Nomade 29x27.5cm', 'PLATOS', 'ALMACÉN', false, null, 0.06, false, false, 'Platos', 91, 406, 0, 'PL04_Llano Gourmet Nomade 29x27.5cm'),
  ('recp05ef3gZcvCBbK', 'PL05_Llano 26cm ANYA iberica Brillo', 'PLATOS', 'ALMACÉN', false, null, 0.06, false, false, 'Platos', 204, 157, 198, 'PL05_Llano 26cm ANYA iberica Brillo'),
  ('recjYJpIhOJ3YSqMW', 'Plato café', 'CAFÉ/TE', 'ALMACÉN', false, null, -0.3, false, false, 'Para Cafés', 168, 238, 213, 'Plato café'),
  ('recfov1swdJgeFZCT', 'Plato Cuadrado (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Plato Cuadrado (PQ)'),
  ('rec00uJWrww49TuCX', 'Plato cuadrado cristal (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Plato cuadrado cristal (PV)'),
  ('recKjFFRwGXpv3qU4', 'Plato de té', 'CAFÉ/TE', 'ALMACÉN', false, null, -0.7, false, false, 'Para Cafés', 177, 65, 66, 'Plato de té'),
  ('recsgmLgr7Wsv9XIb', 'Plato puestos 19x19', null, null, false, null, null, false, false, 'Platos', 544, 400, 488, 'Plato puestos 19x19'),
  ('recknFCCCAd3LZ7eU', 'Plato rectangular (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Plato rectangular (PQ)'),
  ('recvxRWDyKUtiaWvF', 'Plato rectangular (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Plato rectangular (PV)'),
  ('recwgZBe6ow0TorA3', 'Plato rectangular cristal (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Plato rectangular cristal (PV)'),
  ('recywOkWJ7vsQED87', 'Plato redondo (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Plato redondo (PV)'),
  ('recLuyTbbrnB4hFCb', 'Platos (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Platos (PC)'),
  ('recaOhrZRY7ZS58nl', 'Poleo (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Infusiones', 0, 0, 0, 'Poleo (cajas)'),
  ('rec1bnqeiUfBOgy1b', 'Ponchos camareros', 'OTROS', 'ARMARIO DESBARACE', false, null, null, true, true, 'Balda 4', 0, 0, 0, 'Ponchos camareros'),
  ('recbL5fXtk6tex5wS', 'Premium_Atril madera', 'CEREMONIA PREMIUM', 'GENERAL', false, null, null, false, false, 'Ceremonia', 0, 1, 1, 'Premium_Atril madera'),
  ('recUuBTm7nOhsVpK1', 'Premium_Consola madera', 'CEREMONIA PREMIUM', 'GENERAL', false, null, null, false, false, 'Ceremonia', 0, 1, 1, 'Premium_Consola madera'),
  ('recDKHJK8Lm6BTnPt', 'Premium_Sofá Marrón (Chester)', null, null, false, null, null, false, false, 'Ceremonia', 0, 0, 1, 'Premium_Sofá Marrón (Chester)'),
  ('reczvhwkeHYBnShbb', 'Premium_Sofá Verde', null, null, false, null, null, false, false, 'Ceremonia', 0, 1, 1, 'Premium_Sofá Verde'),
  ('rec9xB2Vq5ClJzvI3', 'Producto Lavavajillas', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Producto Lavavajillas'),
  ('recLq6MhKQ0RVFU9G', 'Puerto de Indias Strawberry', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ginebra', 0, 0, 0, 'Puerto de Indias Strawberry'),
  ('recuWySrAhoeb2K6K', 'Puesto 2 Jamon', null, null, false, null, null, false, false, null, 0, 0, 0, 'Puesto 2 Jamon'),
  ('rec5I9h7fKzMFDQNO', 'Rama morada (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Rama morada (PH)'),
  ('rec7utBWxwTyokUp5', 'Rama seca (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Rama seca (PH)'),
  ('reczBs7Dg7cLcX6yz', 'Ramas (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Ramas (PV)'),
  ('recqFtPdmCNCR0Qbc', 'Recambio escoba', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Recambio escoba'),
  ('recFIxiyYBvjqqeqX', 'Recambio mocho', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Recambio mocho'),
  ('rec8eaYZrRDYPV8Lm', 'Recambio mopa', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'Recambio mopa'),
  ('rec0Cy7gwX19zIgyB', 'Recambio recogedor', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Recambio recogedor'),
  ('recNKLkjRQHKPPmpv', 'Recambios aparato mosquitos', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Recambios aparato mosquitos'),
  ('recLebRwkeojpIY3d', 'Recipiente Alargado Negro (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Recipiente Alargado Negro (CB)'),
  ('recbGlUtZLMT8Phvy', 'Recipiente alargado transparente (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Recipiente alargado transparente (CB)'),
  ('recjLnsmWsuCXlj6T', 'Recipiente alargado Transparente 2 secciones (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Recipiente alargado Transparente 2 secciones (CB)'),
  ('rec078DYv0gNoH0oJ', 'Recipiente Negro Mediano (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Recipiente Negro Mediano (CB)'),
  ('recci12LPEUUeHlJV', 'Recipiente Negro Pequeño (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Recipiente Negro Pequeño (CB)'),
  ('recwFdV5XJL2Z8n4J', 'Recipiente Rectangular Transparente (CB)', null, null, false, null, null, false, false, 'Candy Bar', 0, 0, 0, 'Recipiente Rectangular Transparente (CB)'),
  ('recRvyQF52ly3eCuS', 'Recogedor', 'OTROS', 'LIMPIEZA', false, null, null, true, true, 'Utensilios limpieza', 0, 0, 5, 'Recogedor'),
  ('recmnol0I9117kVUy', 'Rectangular blanco 240X350', 'MANTEL', null, false, null, 0.11, false, false, 'Manteles', 17, 4, 5, 'Rectangular blanco 240X350'),
  ('recxTAMofraMGoVJZ', 'Rectangular Madera (2,20x1,00m)', 'MESA', 'GENERAL', false, null, null, false, false, 'Mesas', 1, 11, 7, 'Rectangular Madera (2,20x1,00m)'),
  ('recwdmq9o3kswtH3B', 'Rectangular PVC (1,83x0,76m)', 'MESA', 'GENERAL', false, null, null, false, false, 'Mesas', 2, 5, 8, 'Rectangular PVC (1,83x0,76m)'),
  ('recIZ8FNKp58KDNNl', 'Rectangular PVC (2,00x0,90m)', 'MESA', 'GENERAL', false, null, null, false, false, 'Mesas', 4, 2, 0, 'Rectangular PVC (2,00x0,90m)'),
  ('recujia74Zdsb4rma', 'Red (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Red (PV)'),
  ('rec2aKeauzZNAB4G2', 'Red Label', 'OTROS', 'MAKRO', false, null, null, false, false, 'Whisky', 0, 0, 0, 'Red Label'),
  ('recQXvKuGvJfZjEpN', 'Redonda PVC 1,60m', 'MESA', 'GENERAL', false, null, null, false, false, 'Mesas', 5, 7, 7, 'Redonda PVC 1,60m'),
  ('rec1R4na6tRm8GYRA', 'Redonda PVC 1,80m', 'MESA', 'GENERAL', false, null, null, false, false, 'Mesas', 0, 10, 9, 'Redonda PVC 1,80m'),
  ('recZUlu4FyQUvsuga', 'Redonda PVC 2,00m', 'MESA', 'GENERAL', false, null, null, false, false, 'Mesas', 2, 19, 18, 'Redonda PVC 2,00m'),
  ('rec2HEZCxzksxD2nJ', 'Resto de botellas Ginebra', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ginebra', 0, 0, 0, 'Resto de botellas Ginebra'),
  ('reccGPUIGk68kqGYL', 'Resto de botellas Ron', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ron', 0, 0, 0, 'Resto de botellas Ron'),
  ('receFn74Sl664zzNK', 'Resto de botellas Vodka', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vodka', 0, 0, 0, 'Resto de botellas Vodka'),
  ('rec7vgZFw3rrRXFpz', 'Resto de botellas Whisky', 'OTROS', 'MAKRO', false, null, null, false, false, 'Whisky', 0, 0, 0, 'Resto de botellas Whisky'),
  ('recrdf0UTelSYmNUJ', 'Resto de Cavas', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Cava', 0, 0, 0, 'Resto de Cavas'),
  ('rec8X2yvpGqHu1aO2', 'Resto de Vermut blanco', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Resto de Vermut blanco'),
  ('recSe5VGHfQu2FyIG', 'Resto de Vermut rojo', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Resto de Vermut rojo'),
  ('recYor4rHFqgvfN7p', 'Resto de Vinos Blancos', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Resto de Vinos Blancos'),
  ('recMd643Oyk5VhbUH', 'Resto de Vinos Tintos', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Tinto', 0, 0, 0, 'Resto de Vinos Tintos'),
  ('reczqqNofQe2UtMU3', 'Rigol', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Cava', 0, 0, 0, 'Rigol'),
  ('recGVyCSJDsSagXnh', 'ROJO - Oasis Premium - Desinfectante ácido (baños)', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 4', 0, 0, 0, 'ROJO - Oasis Premium - Desinfectante ácido (baños)'),
  ('recErBBPkEYO4NIVf', 'Sacarina (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Endulzantes y Lácteos', 0, 0, 0, 'Sacarina (cajas)'),
  ('recl5QyGq8F6tVkQf', 'Salvamantel (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Salvamantel (PQ)'),
  ('recGTgZMt4yNvdThV', 'Salvamantel grande (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Salvamantel grande (PA)'),
  ('rec10EkLReVRZ4UD5', 'Salvamantel grande(PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Salvamantel grande(PH)'),
  ('recPYGs6yeDsXsLic', 'Salvamantel peque (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Salvamantel peque (PH)'),
  ('recebWmKaJZL74MXT', 'Salvamanteles (PC)', null, null, false, null, null, false, false, 'Puesto Croquetas', 0, 0, 0, 'Salvamanteles (PC)'),
  ('recd6sw6xGku26mkg', 'Salvamanteles Pequeños (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Salvamanteles Pequeños (PA)'),
  ('reczB84NVNNYKEmbo', 'Santa Teresa', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ron', 0, 0, 0, 'Santa Teresa'),
  ('recht2s1ISoTC2WAw', 'Scott Control Higiénico WC', 'OTROS', 'ARMARIO LIMPIEZA', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Scott Control Higiénico WC'),
  ('recwDi5ZB2CmAt2iR', 'Seagram’s', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ginebra', 0, 0, 0, 'Seagram’s'),
  ('rec5wOixffhdApvGV', 'Seagram''s 0,0%', 'OTROS', 'MAKRO', false, null, null, false, false, 'Sin Alcohol (0,0%)', 0, 0, 0, 'Seagram''s 0,0%'),
  ('recUfBh8J700YMy3g', 'Servilleta vinchy (PA)', null, null, false, null, null, false, false, 'Puesto Arroces', 0, 0, 0, 'Servilleta vinchy (PA)'),
  ('recxQw38RRV55Jy74', 'Servilletas negras coctel', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Servilletas negras coctel'),
  ('recVogQsqyCDb8jHT', 'Servilleteros', 'OTROS', 'ARMARIO EVENTO', false, null, null, true, true, 'Útiles Coctel / Fiesta', 0, 0, 0, 'Servilleteros'),
  ('recU15STNGu51tUpV', 'Setas Coctel (mesas altas)', 'MESA', 'GENERAL', false, null, null, false, false, 'Útiles Coctel / Fiesta', 0, 17, 14, 'Setas Coctel (mesas altas)'),
  ('recLd7GmsgSsmhlDl', 'Sillón madera 1 pax', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 0, 6, 12, 'Sillón madera 1 pax'),
  ('recwWKK8eygXcnjin', 'Smirnoff', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vodka', 0, 0, 0, 'Smirnoff'),
  ('recjRiiy39wPq8dLQ', 'Sofa madera 2 pax', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 0, 6, 12, 'Sofa madera 2 pax'),
  ('rec342o0bIW8zkQQf', 'Sombrillas', 'SOMBRILLAS', 'GENERAL', false, null, null, false, true, 'Útiles Coctel / Fiesta', 0, 6, 8, 'Sombrillas'),
  ('recXtNpQkbUjVEhKS', 'Spray antimosquitos', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Spray antimosquitos'),
  ('rececSAy2tcsVeg8I', 'Sprite', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Sprite'),
  ('recRew792NXQdr4FF', 'Sutra', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Cava', 0, 0, 0, 'Sutra'),
  ('recQRDaTeNDO1mj6j', 'Tabla (PV) | Puesto Vermut', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Tabla (PV)'),
  ('recMMPkbulvXw7jXs', 'Tabla (PV) [Xw7jXs]', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Tabla (PV)'),
  ('reczHF3j0FiQ6yGC6', 'Tabla Pequeña (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Tabla Pequeña (PQ)'),
  ('recyDNs5Bgm0GTBH6', 'Taburete mimbre', 'TABURETE', 'ALMACÉN', false, null, null, false, true, 'Útiles Coctel / Fiesta', 28, 30, 34, 'Taburete mimbre'),
  ('recNMrqOHHfy6NusZ', 'Tallada_Copa Blanco', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas Vino / Cava', 397, 200, 179, 'Tallada_Copa Blanco'),
  ('rec3KhIuYYwDNknr3', 'Tallada_Copa Cava', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas Vino / Cava', 60, 180, 384, 'Tallada_Copa Cava'),
  ('reccmTkDp7SeDHYHU', 'Tallada_Copa Tinto', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas Vino / Cava', 385, 192, 176, 'Tallada_Copa Tinto'),
  ('rec1o36fD0JD74Pd1', 'Tampones 01', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Tampones 01'),
  ('recata9u8NJGQTnZE', 'Tanqueray', 'OTROS', 'MAKRO', false, null, null, false, false, 'Ginebra', 0, 0, 0, 'Tanqueray'),
  ('recvaXFxN8L10FeTz', 'Tanqueray 0,0%', 'OTROS', 'MAKRO', false, null, null, false, false, 'Sin Alcohol (0,0%)', 0, 0, 0, 'Tanqueray 0,0%'),
  ('recg5mIQ73e3w3shO', 'Tapa grande y peque (PS)', null, null, false, null, null, false, false, 'Puesto Sushi', 0, 0, 0, 'Tapa grande y peque (PS)'),
  ('recKMFBRxQTNhxUo7', 'Tarrito con paja (PH)', null, null, false, null, null, false, false, 'Puesto Huevos', 0, 0, 0, 'Tarrito con paja (PH)'),
  ('recOyYdmk2Q3x9OkY', 'Taza de café', 'CAFÉ/TE', 'ALMACÉN', false, null, -0.3, false, false, 'Para Cafés', 176, 225, 177, 'Taza de café'),
  ('recPlp93Bt2od1TeV', 'Taza té', 'CAFÉ/TE', 'ALMACÉN', false, null, -0.7, false, false, 'Para Cafés', 40, 112, 69, 'Taza té'),
  ('recJDwww4FkHdpOQ8', 'Te verde (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Infusiones', 0, 0, 0, 'Te verde (cajas)'),
  ('rectFBBC9eQxYHtrn', 'Tequifresi', 'OTROS', 'MAKRO', false, null, null, false, false, 'Chupitos', 0, 0, 0, 'Tequifresi'),
  ('recanPaNq1sWXp5ah', 'Terracota', 'SERVILLETAS', 'TELAS', false, null, 0.05, false, false, 'Servilletas', 393, 0, 0, 'Terracota'),
  ('recrUOfkzwIp5jBUH', 'Terry Centenario', 'OTROS', 'MAKRO', false, null, null, false, false, 'Para Cafés', 0, 0, 0, 'Terry Centenario'),
  ('recXP2v9xbYCqwLFb', 'Thai', 'BAJOPLATO', 'ALMACÉN', false, 'https://v5.airtableusercontent.com/v3/u/52/52/1775592000000/v-XV5FFSs1A9JVUcsX3Tdg/d9ee6Ecq7pjRBOyE1i8ye6pf_B_p7fMkTAO79qPbqmE8CkKbDEKFqa-uPs_hxEB2UIc7fSo76LnN1bj3G-mIcrN2YAftXtua1Yj5u6OxahLycmnPZbuO4RiODJPcSX5rYIq7pzXrHXx3_-AwkTkDPDonieRWI5qID7fe8NHDPZ4j7_Omonr8S93Ot90_AV6I0_6Z3XJD1mCmDLYkPF5Nxg/bkFYZS-gjkQPP_38CzaU8pm5r589l58p36I2V05nJGo', 0.05, false, false, 'Bajoplato', 340, 0, 180, 'Thai'),
  ('recUuLMckxlZixIcR', 'Tijeras', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 2', 0, 0, 0, 'Tijeras'),
  ('rec2BbxF4CYp3zNxi', 'Tila (cajas)', 'OTROS', 'MAKRO', false, null, null, false, false, 'Infusiones', 0, 0, 0, 'Tila (cajas)'),
  ('recLOE64Y1iXCXgGo', 'Tinto de Verano', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Tinto de Verano'),
  ('recJ2CmaDR5ok1uVA', 'Tiradores de cerveza', 'OTROS', 'EVENTO', false, null, null, true, true, 'EVENTO', 0, 2, 2, 'Tiradores de cerveza'),
  ('recjXAjFJuZP2PoGp', 'Tiritas', 'OTROS', 'AMENITIES', false, null, null, true, true, 'Amenities', 0, 0, 0, 'Tiritas'),
  ('rec9BDNQtzYOwdWpW', 'Tónica', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Refrescos', 0, 0, 0, 'Tónica'),
  ('recPJDJfdw5I7lmZm', 'Trapo limpiado', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Trapo limpiado'),
  ('recJJu8UlbeMQPZr3', 'Trapo secado', 'OTROS', 'ARMARIO DESBARACE', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Trapo secado'),
  ('recI46nVKNnfcm8em', 'Tronas', 'OTROS', 'EVENTO', false, null, null, true, true, 'EVENTO', 3, 7, 3, 'Tronas'),
  ('recFwTxdRYcb5pxQQ', 'Tronco (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'Tronco (PQ)'),
  ('rec9hI3f0EpigbUN9', 'tronco altura (PQ)', null, null, false, null, null, false, false, 'Puesto Quesos Clasicos', 0, 0, 0, 'tronco altura (PQ)'),
  ('rec7icna8B6V2qNcA', 'Turia', 'OTROS', 'COCA-COLA', false, null, null, false, false, 'Cerveza', 0, 0, 0, 'Turia'),
  ('recmFzA5X2KNv13nI', 'V1_Funda blanca respaldo', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 51, 0, 0, 'V1_Funda blanca respaldo'),
  ('recLKDQYkpxS5knHD', 'V1_Funda blanca sillón pequeña', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 25, 0, 0, 'V1_Funda blanca sillón pequeña'),
  ('recZDr6MAX6uoGlPn', 'V1_Funda blanca sofa grande', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 24, 0, 0, 'V1_Funda blanca sofa grande'),
  ('recrzYKlZvyoZDEjy', 'V2_Funda blanca respaldo', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 0, 0, 0, 'V2_Funda blanca respaldo'),
  ('rec5QmsPiGuOZVLMT', 'V2_Funda blanca sillón pequeña', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 0, 0, 0, 'V2_Funda blanca sillón pequeña'),
  ('recdqsb1WsUu1YX4v', 'V2_Funda blanca sofa grande', 'CHILLLOUT', 'GENERAL', false, null, null, false, false, 'Chill Out', 0, 0, 0, 'V2_Funda blanca sofa grande'),
  ('recsqibX9MYYdZhcO', 'Valdubon', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Tinto', 0, 0, 0, 'Valdubon'),
  ('recrYOTDhALsO5izG', 'Vaso de sidra', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Útiles Coctel / Fiesta', 576, 670, 571, 'Vaso de sidra'),
  ('recPrDWPQKLd5nZEF', 'Vaso grande (PV)', null, null, false, null, null, false, false, 'Puesto Vermut', 0, 0, 0, 'Vaso grande (PV)'),
  ('recmsPiT3uufuoLr5', 'Vaso pinta', 'CRISTALERIA', null, false, null, null, false, false, 'Ceremonia', 353, 230, 275, 'Vaso pinta'),
  ('receLxQEVjo9fo1e9', 'Vaso Trocado transparente', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas / Vasos Agua', 0, 200, 198, 'Vaso Trocado transparente'),
  ('recgx1rvpSoiouh3h', 'Vaso Venecia ahumado/gris', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas / Vasos Agua', 387, 0, 0, 'Vaso Venecia ahumado/gris'),
  ('recV9JBQ68Z9frgss', 'Vaso Venecia Transparente', 'CRISTALERIA', 'ALMACÉN', false, null, 0.06, false, false, 'Copas / Vasos Agua', 303, 0, 200, 'Vaso Venecia Transparente'),
  ('recaxac1KVsuueDiS', 'Vasos de chupitos', 'OTROS', 'ARMARIO EVENTO', false, null, null, false, false, 'Balda 1', 0, 0, 0, 'Vasos de chupitos'),
  ('recolsbo4AUZP8mdO', 'Verde eucalipto', 'MANTEL', 'TELAS', false, null, 0.05, false, false, 'Manteles', 65, 8, 0, 'Verde eucalipto'),
  ('recL7leF8ZUH0jpqO', 'Vertedores de botella (PM)', null, null, false, null, null, false, false, 'Puesto Mojitos', 0, 0, 0, 'Vertedores de botella (PM)'),
  ('recIwuj4WPft0Gk9Y', 'Vichy negro', 'MANTEL', 'TELAS', false, null, 0.05, false, false, 'Manteles', 37, 0, 10, 'Vichy negro'),
  ('recUBrZIja97tHkaU', 'Vichy negro cuadro pequeño', 'SERVILLETAS', 'TELAS', false, null, 0.05, false, false, 'Servilletas', 275, 0, 0, 'Vichy negro cuadro pequeño'),
  ('rec3px9BP7JAhumrW', 'Vittore blanco', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut', 0, 0, 0, 'Vittore blanco'),
  ('recF1X3q3KF4LTebM', 'Vittore rojo', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut', 0, 0, 0, 'Vittore rojo'),
  ('rec4PmKe4DHellPDH', 'Vivanco blanco', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Blanco', 0, 0, 0, 'Vivanco blanco'),
  ('recPG96MWYnDOLq6x', 'Vivanco crianza', 'OTROS', 'BODEGA NAVARRO', false, null, null, false, false, 'Vino Tinto', 0, 0, 0, 'Vivanco crianza'),
  ('recXuBQelQwh7VPtS', 'Walkie talkies', 'OTROS', 'ARMARIO EVENTO', false, null, null, true, true, 'Balda 3', 23, 19, 16, 'Walkie talkies'),
  ('recxojn9kQisE5wmV', 'Yzaguirre blanco', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Yzaguirre blanco'),
  ('recnQin1wSFnqLUAb', 'Yzaguirre rojo', 'OTROS', 'MAKRO', false, null, null, false, false, 'Vermut (marcas del puesto)', 0, 0, 0, 'Yzaguirre rojo');
insert into logistica_tareas.articulos (
  airtable_record_id, nombre, tipologia, formulario, paquete, imagen_url, coeficiente, objeto_comun, minimo_comun, subgrupo
)
select
  s.airtable_record_id, s.nombre, s.tipologia, s.formulario, s.paquete, s.imagen_url, coalesce(s.coeficiente, 0), s.objeto_comun, s.minimo_comun, s.subgrupo
from _lt_airtable_inventory_import s
on conflict (airtable_record_id) do update
set
  nombre = excluded.nombre,
  tipologia = excluded.tipologia,
  formulario = excluded.formulario,
  paquete = excluded.paquete,
  imagen_url = excluded.imagen_url,
  coeficiente = excluded.coeficiente,
  objeto_comun = excluded.objeto_comun,
  minimo_comun = excluded.minimo_comun,
  subgrupo = excluded.subgrupo,
  updated_at = timezone('utc', now());
with espacios as (
  select id, codigo
  from logistica_tareas.espacios
  where codigo in ('centro_produccion', 'huerta', 'torre')
), articulos as (
  select id, airtable_record_id
  from logistica_tareas.articulos
  where airtable_record_id in (select airtable_record_id from _lt_airtable_inventory_import)
), inventory_source as (
  select a.id as articulo_id, e.id as espacio_id, s.stock_cp as cantidad
  from _lt_airtable_inventory_import s
  join articulos a on a.airtable_record_id = s.airtable_record_id
  join espacios e on e.codigo = 'centro_produccion'
  union all
  select a.id as articulo_id, e.id as espacio_id, s.stock_hu as cantidad
  from _lt_airtable_inventory_import s
  join articulos a on a.airtable_record_id = s.airtable_record_id
  join espacios e on e.codigo = 'huerta'
  union all
  select a.id as articulo_id, e.id as espacio_id, s.stock_to as cantidad
  from _lt_airtable_inventory_import s
  join articulos a on a.airtable_record_id = s.airtable_record_id
  join espacios e on e.codigo = 'torre'
)
insert into logistica_tareas.inventario (espacio_id, articulo_id, cantidad)
select espacio_id, articulo_id, greatest(cantidad, 0)
from inventory_source
on conflict (espacio_id, articulo_id) do update
set
  cantidad = excluded.cantidad,
  updated_at = timezone('utc', now());
