do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'logistica_tareas'
      and t.typname = 'espacio_rol'
  ) then
    create type logistica_tareas.espacio_rol as enum ('evento', 'almacen');
  end if;

  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'logistica_tareas'
      and t.typname = 'planner_estado'
  ) then
    create type logistica_tareas.planner_estado as enum ('borrador', 'planificado', 'ruptura', 'cancelado');
  end if;

  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'logistica_tareas'
      and t.typname = 'requerimiento_estado'
  ) then
    create type logistica_tareas.requerimiento_estado as enum ('cubierto', 'ruptura');
  end if;

  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'logistica_tareas'
      and t.typname = 'tarea_estado'
  ) then
    create type logistica_tareas.tarea_estado as enum ('pendiente', 'en_proceso', 'completada', 'cancelada');
  end if;

  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'logistica_tareas'
      and t.typname = 'movimiento_tipo'
  ) then
    create type logistica_tareas.movimiento_tipo as enum ('reserva_local', 'reserva_traslado', 'liberacion', 'traslado_completado');
  end if;

  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'logistica_tareas'
      and t.typname = 'movimiento_estado'
  ) then
    create type logistica_tareas.movimiento_estado as enum ('activo', 'cancelado', 'aplicado');
  end if;
end;
$$;
create or replace function logistica_tareas.touch_updated_at()
returns trigger
language plpgsql
as $function$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$function$;
create or replace function logistica_tareas.week_start(p_fecha date)
returns date
language sql
immutable
as $function$
  select (p_fecha - ((extract(isodow from p_fecha)::int) - 1))::date;
$function$;
create or replace function logistica_tareas.week_end(p_fecha date)
returns date
language sql
immutable
as $function$
  select (logistica_tareas.week_start(p_fecha) + 6)::date;
$function$;
alter table if exists logistica_tareas.espacios
  add column if not exists codigo text,
  add column if not exists rol logistica_tareas.espacio_rol,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());
update logistica_tareas.espacios
set
  codigo = case
    when lower(trim(nombre)) = 'torre' then 'torre'
    when lower(trim(nombre)) = 'huerta' then 'huerta'
    when lower(trim(nombre)) = 'pueblo' then 'pueblo'
    when lower(trim(nombre)) in ('centro de produccion', 'cp') then 'centro_produccion'
    else codigo
  end,
  rol = case
    when lower(trim(nombre)) in ('torre', 'huerta', 'pueblo') then 'evento'::logistica_tareas.espacio_rol
    when lower(trim(nombre)) in ('centro de produccion', 'cp') then 'almacen'::logistica_tareas.espacio_rol
    else rol
  end,
  updated_at = timezone('utc', now())
where codigo is null or rol is null;
create unique index if not exists espacios_codigo_uidx
  on logistica_tareas.espacios (codigo)
  where codigo is not null;
insert into logistica_tareas.espacios (nombre, codigo, rol)
select v.nombre, v.codigo, v.rol
from (
  values
    ('Torre', 'torre', 'evento'::logistica_tareas.espacio_rol),
    ('Huerta', 'huerta', 'evento'::logistica_tareas.espacio_rol),
    ('Pueblo', 'pueblo', 'evento'::logistica_tareas.espacio_rol),
    ('Centro de Produccion', 'centro_produccion', 'almacen'::logistica_tareas.espacio_rol)
) as v(nombre, codigo, rol)
where not exists (
  select 1
  from logistica_tareas.espacios e
  where e.codigo = v.codigo
);
create table if not exists logistica_tareas.novios (
  id bigint generated by default as identity primary key,
  novio text,
  novia text,
  nombre_completo text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint novios_nombre_completo_key unique (nombre_completo)
);
create table if not exists logistica_tareas.articulos (
  id bigint generated by default as identity primary key,
  airtable_record_id text,
  nombre text not null,
  tipologia text,
  formulario text,
  paquete boolean not null default false,
  imagen_url text,
  coeficiente numeric(12,4) not null default 0,
  objeto_comun boolean not null default false,
  minimo_comun boolean not null default false,
  segmento_inventario smallint,
  subgrupo text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint articulos_nombre_key unique (nombre),
  constraint articulos_airtable_record_id_key unique (airtable_record_id),
  constraint articulos_segmento_inventario_check check (
    segmento_inventario is null
    or (segmento_inventario between 1 and 9)
  )
);
create table if not exists logistica_tareas.articulo_componentes (
  id bigint generated by default as identity primary key,
  articulo_paquete_id bigint not null references logistica_tareas.articulos (id) on delete cascade,
  articulo_componente_id bigint not null references logistica_tareas.articulos (id) on delete restrict,
  cantidad_componente integer not null check (cantidad_componente > 0),
  created_at timestamptz not null default timezone('utc', now()),
  constraint articulo_componentes_unique unique (articulo_paquete_id, articulo_componente_id),
  constraint articulo_componentes_distinct_check check (articulo_paquete_id <> articulo_componente_id)
);
create table if not exists logistica_tareas.inventario (
  id bigint generated by default as identity primary key,
  espacio_id bigint not null references logistica_tareas.espacios (id) on delete cascade,
  articulo_id bigint not null references logistica_tareas.articulos (id) on delete cascade,
  cantidad integer not null default 0 check (cantidad >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint inventario_unique unique (espacio_id, articulo_id)
);
create table if not exists logistica_tareas.prioridades_abastecimiento (
  id bigint generated by default as identity primary key,
  espacio_evento_id bigint not null references logistica_tareas.espacios (id) on delete cascade,
  espacio_fuente_id bigint not null references logistica_tareas.espacios (id) on delete cascade,
  prioridad smallint not null check (prioridad > 0),
  created_at timestamptz not null default timezone('utc', now()),
  constraint prioridades_abastecimiento_unique_prioridad unique (espacio_evento_id, prioridad),
  constraint prioridades_abastecimiento_unique_fuente unique (espacio_evento_id, espacio_fuente_id),
  constraint prioridades_abastecimiento_distinct_check check (espacio_evento_id <> espacio_fuente_id)
);
create table if not exists logistica_tareas.planner_eventos (
  id bigint generated by default as identity primary key,
  external_event_id text not null,
  nombre text not null,
  novios_id bigint not null references logistica_tareas.novios (id) on delete restrict,
  espacio_evento_id bigint not null references logistica_tareas.espacios (id) on delete restrict,
  fecha_evento date not null,
  semana_operativa_inicio date not null,
  semana_operativa_fin date not null,
  plan_version integer not null default 1 check (plan_version >= 1),
  estado_planificacion logistica_tareas.planner_estado not null default 'borrador',
  ruptura_inventario boolean not null default false,
  last_payload jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_eventos_external_event_id_key unique (external_event_id),
  constraint planner_eventos_week_bounds_check check (semana_operativa_fin = semana_operativa_inicio + 6)
);
create table if not exists logistica_tareas.planner_lineas (
  id bigint generated by default as identity primary key,
  planner_evento_id bigint not null references logistica_tareas.planner_eventos (id) on delete cascade,
  plan_version integer not null check (plan_version >= 1),
  external_line_id text not null,
  articulo_id bigint not null references logistica_tareas.articulos (id) on delete restrict,
  requeridos_iniciales integer not null check (requeridos_iniciales > 0),
  requeridos_finales integer not null check (requeridos_finales > 0),
  created_at timestamptz not null default timezone('utc', now()),
  constraint planner_lineas_unique unique (planner_evento_id, plan_version, external_line_id)
);
create index if not exists planner_lineas_evento_version_idx
  on logistica_tareas.planner_lineas (planner_evento_id, plan_version);
create table if not exists logistica_tareas.planner_requerimientos (
  id bigint generated by default as identity primary key,
  planner_evento_id bigint not null references logistica_tareas.planner_eventos (id) on delete cascade,
  plan_version integer not null check (plan_version >= 1),
  planner_linea_id bigint not null references logistica_tareas.planner_lineas (id) on delete cascade,
  articulo_solicitado_id bigint not null references logistica_tareas.articulos (id) on delete restrict,
  articulo_id bigint not null references logistica_tareas.articulos (id) on delete restrict,
  cantidad_requerida integer not null check (cantidad_requerida > 0),
  cantidad_reservada_local integer not null default 0 check (cantidad_reservada_local >= 0),
  cantidad_asignada_externa integer not null default 0 check (cantidad_asignada_externa >= 0),
  cantidad_en_ruptura integer not null default 0 check (cantidad_en_ruptura >= 0),
  estado_cobertura logistica_tareas.requerimiento_estado not null default 'cubierto',
  detalle_cobertura jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);
create index if not exists planner_requerimientos_evento_version_idx
  on logistica_tareas.planner_requerimientos (planner_evento_id, plan_version);
create table if not exists logistica_tareas.tareas (
  id bigint generated by default as identity primary key,
  planner_evento_id bigint not null references logistica_tareas.planner_eventos (id) on delete cascade,
  plan_version integer not null check (plan_version >= 1),
  planner_requerimiento_id bigint not null references logistica_tareas.planner_requerimientos (id) on delete cascade,
  remitente_espacio_id bigint not null references logistica_tareas.espacios (id) on delete restrict,
  receptor_espacio_id bigint not null references logistica_tareas.espacios (id) on delete restrict,
  articulo_id bigint not null references logistica_tareas.articulos (id) on delete restrict,
  cantidad integer not null check (cantidad > 0),
  estado logistica_tareas.tarea_estado not null default 'pendiente',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  cancelled_at timestamptz,
  constraint tareas_origen_destino_check check (remitente_espacio_id <> receptor_espacio_id)
);
create index if not exists tareas_evento_version_idx
  on logistica_tareas.tareas (planner_evento_id, plan_version, estado);
create table if not exists logistica_tareas.inventario_movimientos (
  id bigint generated by default as identity primary key,
  planner_evento_id bigint not null references logistica_tareas.planner_eventos (id) on delete cascade,
  plan_version integer not null check (plan_version >= 1),
  planner_requerimiento_id bigint references logistica_tareas.planner_requerimientos (id) on delete set null,
  tarea_id bigint references logistica_tareas.tareas (id) on delete set null,
  semana_operativa_inicio date not null,
  tipo logistica_tareas.movimiento_tipo not null,
  estado logistica_tareas.movimiento_estado not null default 'activo',
  espacio_origen_id bigint not null references logistica_tareas.espacios (id) on delete restrict,
  espacio_destino_id bigint references logistica_tareas.espacios (id) on delete restrict,
  articulo_id bigint not null references logistica_tareas.articulos (id) on delete restrict,
  cantidad integer not null check (cantidad > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  cancelled_at timestamptz,
  applied_at timestamptz
);
create index if not exists inventario_movimientos_disponibilidad_idx
  on logistica_tareas.inventario_movimientos (semana_operativa_inicio, espacio_origen_id, articulo_id, estado);
drop trigger if exists tr_espacios_touch_updated_at on logistica_tareas.espacios;
create trigger tr_espacios_touch_updated_at
before update on logistica_tareas.espacios
for each row execute function logistica_tareas.touch_updated_at();
drop trigger if exists tr_novios_touch_updated_at on logistica_tareas.novios;
create trigger tr_novios_touch_updated_at
before update on logistica_tareas.novios
for each row execute function logistica_tareas.touch_updated_at();
drop trigger if exists tr_articulos_touch_updated_at on logistica_tareas.articulos;
create trigger tr_articulos_touch_updated_at
before update on logistica_tareas.articulos
for each row execute function logistica_tareas.touch_updated_at();
drop trigger if exists tr_inventario_touch_updated_at on logistica_tareas.inventario;
create trigger tr_inventario_touch_updated_at
before update on logistica_tareas.inventario
for each row execute function logistica_tareas.touch_updated_at();
drop trigger if exists tr_planner_eventos_touch_updated_at on logistica_tareas.planner_eventos;
create trigger tr_planner_eventos_touch_updated_at
before update on logistica_tareas.planner_eventos
for each row execute function logistica_tareas.touch_updated_at();
drop trigger if exists tr_tareas_touch_updated_at on logistica_tareas.tareas;
create trigger tr_tareas_touch_updated_at
before update on logistica_tareas.tareas
for each row execute function logistica_tareas.touch_updated_at();
drop trigger if exists tr_inventario_movimientos_touch_updated_at on logistica_tareas.inventario_movimientos;
create trigger tr_inventario_movimientos_touch_updated_at
before update on logistica_tareas.inventario_movimientos
for each row execute function logistica_tareas.touch_updated_at();
insert into logistica_tareas.prioridades_abastecimiento (espacio_evento_id, espacio_fuente_id, prioridad)
select evento.id, fuente.id, prioridad.prioridad
from (
  values
    ('torre', 'pueblo', 1),
    ('torre', 'huerta', 2),
    ('pueblo', 'torre', 1),
    ('pueblo', 'huerta', 2),
    ('huerta', 'torre', 1),
    ('huerta', 'pueblo', 2)
) as prioridad(evento_codigo, fuente_codigo, prioridad)
join logistica_tareas.espacios evento on evento.codigo = prioridad.evento_codigo
join logistica_tareas.espacios fuente on fuente.codigo = prioridad.fuente_codigo
on conflict (espacio_evento_id, prioridad)
do update set espacio_fuente_id = excluded.espacio_fuente_id;
create or replace function logistica_tareas.ensure_inventory_row(
  p_espacio_id bigint,
  p_articulo_id bigint
)
returns void
language plpgsql
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
begin
  insert into logistica_tareas.inventario (espacio_id, articulo_id, cantidad)
  values (p_espacio_id, p_articulo_id, 0)
  on conflict (espacio_id, articulo_id) do nothing;
end;
$function$;
create or replace function logistica_tareas.available_quantity(
  p_espacio_id bigint,
  p_articulo_id bigint,
  p_semana_operativa_inicio date
)
returns integer
language sql
stable
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
  with base as (
    select cantidad
    from logistica_tareas.inventario
    where espacio_id = p_espacio_id
      and articulo_id = p_articulo_id
  ),
  reservado as (
    select coalesce(sum(cantidad), 0) as total
    from logistica_tareas.inventario_movimientos
    where espacio_origen_id = p_espacio_id
      and articulo_id = p_articulo_id
      and semana_operativa_inicio = p_semana_operativa_inicio
      and estado = 'activo'::logistica_tareas.movimiento_estado
  )
  select greatest(coalesce((select cantidad from base), 0) - (select total from reservado), 0)::integer;
$function$;
create or replace function logistica_tareas.resolve_articulo_ref(
  p_articulo_ref text
)
returns bigint
language plpgsql
stable
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
declare
  v_articulo_id bigint;
  v_ref text := nullif(trim(p_articulo_ref), '');
begin
  if v_ref is null then
    raise exception 'articulo_ref es obligatorio';
  end if;

  if v_ref ~ '^\d+$' then
    select id
    into v_articulo_id
    from logistica_tareas.articulos
    where id = v_ref::bigint;
  end if;

  if v_articulo_id is null then
    select id
    into v_articulo_id
    from logistica_tareas.articulos
    where airtable_record_id = v_ref;
  end if;

  if v_articulo_id is null then
    select id
    into v_articulo_id
    from logistica_tareas.articulos
    where lower(nombre) = lower(v_ref);
  end if;

  if v_articulo_id is null then
    raise exception 'No se encontro articulo para referencia: %', v_ref;
  end if;

  return v_articulo_id;
end;
$function$;
create or replace function logistica_tareas.get_or_create_novios(
  p_novio text,
  p_novia text,
  p_nombre_evento text
)
returns bigint
language plpgsql
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
declare
  v_nombre_completo text;
  v_novios_id bigint;
begin
  v_nombre_completo := nullif(
    trim(
      concat_ws(' & ', nullif(trim(coalesce(p_novio, '')), ''), nullif(trim(coalesce(p_novia, '')), ''))
    ),
    ''
  );

  if v_nombre_completo is null then
    v_nombre_completo := coalesce(nullif(trim(p_nombre_evento), ''), 'Sin nombre');
  end if;

  insert into logistica_tareas.novios (novio, novia, nombre_completo)
  values (nullif(trim(coalesce(p_novio, '')), ''), nullif(trim(coalesce(p_novia, '')), ''), v_nombre_completo)
  on conflict (nombre_completo)
  do update
  set
    novio = excluded.novio,
    novia = excluded.novia,
    updated_at = timezone('utc', now())
  returning id into v_novios_id;

  return v_novios_id;
end;
$function$;
create or replace function logistica_tareas.create_transfer_task(
  p_planner_evento_id bigint,
  p_plan_version integer,
  p_planner_requerimiento_id bigint,
  p_semana_operativa_inicio date,
  p_remitente_espacio_id bigint,
  p_receptor_espacio_id bigint,
  p_articulo_id bigint,
  p_cantidad integer
)
returns bigint
language plpgsql
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
declare
  v_tarea_id bigint;
begin
  if p_cantidad is null or p_cantidad <= 0 then
    raise exception 'La cantidad de la tarea debe ser mayor a cero';
  end if;

  insert into logistica_tareas.tareas (
    planner_evento_id,
    plan_version,
    planner_requerimiento_id,
    remitente_espacio_id,
    receptor_espacio_id,
    articulo_id,
    cantidad,
    estado
  )
  values (
    p_planner_evento_id,
    p_plan_version,
    p_planner_requerimiento_id,
    p_remitente_espacio_id,
    p_receptor_espacio_id,
    p_articulo_id,
    p_cantidad,
    'pendiente'
  )
  returning id into v_tarea_id;

  insert into logistica_tareas.inventario_movimientos (
    planner_evento_id,
    plan_version,
    planner_requerimiento_id,
    tarea_id,
    semana_operativa_inicio,
    tipo,
    estado,
    espacio_origen_id,
    espacio_destino_id,
    articulo_id,
    cantidad
  )
  values (
    p_planner_evento_id,
    p_plan_version,
    p_planner_requerimiento_id,
    v_tarea_id,
    p_semana_operativa_inicio,
    'reserva_traslado',
    'activo',
    p_remitente_espacio_id,
    p_receptor_espacio_id,
    p_articulo_id,
    p_cantidad
  );

  return v_tarea_id;
end;
$function$;
create or replace function logistica_tareas.cancel_active_plan(
  p_planner_evento_id bigint,
  p_plan_version integer
)
returns void
language plpgsql
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
begin
  update logistica_tareas.tareas
  set
    estado = 'cancelada',
    cancelled_at = timezone('utc', now()),
    updated_at = timezone('utc', now())
  where planner_evento_id = p_planner_evento_id
    and plan_version = p_plan_version
    and estado in ('pendiente', 'en_proceso');

  update logistica_tareas.inventario_movimientos
  set
    estado = 'cancelado',
    cancelled_at = timezone('utc', now()),
    updated_at = timezone('utc', now())
  where planner_evento_id = p_planner_evento_id
    and plan_version = p_plan_version
    and estado = 'activo';
end;
$function$;
create or replace function logistica_tareas.sync_planner_event(
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
declare
  v_external_event_id text := nullif(trim(p_payload ->> 'external_event_id'), '');
  v_nombre_evento text := coalesce(nullif(trim(p_payload ->> 'nombre_evento'), ''), 'Evento sin nombre');
  v_fecha_evento date := nullif(trim(p_payload ->> 'fecha_evento'), '')::date;
  v_espacio_codigo text := nullif(trim(p_payload ->> 'espacio_codigo'), '');
  v_novio text := p_payload ->> 'novio';
  v_novia text := p_payload ->> 'novia';
  v_lineas jsonb := p_payload -> 'lineas';
  v_novios_id bigint;
  v_espacio_evento_id bigint;
  v_planner_evento_id bigint;
  v_previous_version integer;
  v_plan_version integer;
  v_semana_operativa_inicio date;
  v_semana_operativa_fin date;
  v_cp_id bigint;
  v_tiene_ruptura boolean := false;
  v_requirements jsonb;
  v_tasks jsonb;
  v_linea jsonb;
  v_linea_id bigint;
  v_articulo_id bigint;
  v_external_line_id text;
  v_requeridos_iniciales integer;
  v_requeridos_finales integer;
  v_requerimiento record;
  v_prioridad record;
  v_local_disponible integer;
  v_reserva_local integer;
  v_faltante integer;
  v_cp_disponible integer;
  v_fuente_1_id bigint;
  v_fuente_2_id bigint;
  v_fuente_1_disponible integer;
  v_fuente_2_disponible integer;
  v_asignado_externo integer;
  v_detalle jsonb;
  v_total_disponible integer;
  v_asignar integer;
begin
  if jsonb_typeof(p_payload) <> 'object' then
    raise exception 'El payload debe ser un objeto JSON';
  end if;

  if v_external_event_id is null then
    raise exception 'external_event_id es obligatorio';
  end if;

  if v_fecha_evento is null then
    raise exception 'fecha_evento es obligatoria';
  end if;

  if v_espacio_codigo is null then
    raise exception 'espacio_codigo es obligatorio';
  end if;

  if jsonb_typeof(v_lineas) <> 'array' or jsonb_array_length(v_lineas) = 0 then
    raise exception 'lineas debe ser un arreglo no vacio';
  end if;

  select id
  into v_espacio_evento_id
  from logistica_tareas.espacios
  where codigo = v_espacio_codigo
    and rol = 'evento'::logistica_tareas.espacio_rol;

  if v_espacio_evento_id is null then
    raise exception 'No se encontro un espacio de evento valido para codigo: %', v_espacio_codigo;
  end if;

  select id
  into v_cp_id
  from logistica_tareas.espacios
  where codigo = 'centro_produccion'
    and rol = 'almacen'::logistica_tareas.espacio_rol;

  if v_cp_id is null then
    raise exception 'No existe el espacio centro_produccion configurado';
  end if;

  v_novios_id := logistica_tareas.get_or_create_novios(v_novio, v_novia, v_nombre_evento);
  v_semana_operativa_inicio := logistica_tareas.week_start(v_fecha_evento);
  v_semana_operativa_fin := logistica_tareas.week_end(v_fecha_evento);

  select id, plan_version
  into v_planner_evento_id, v_previous_version
  from logistica_tareas.planner_eventos
  where external_event_id = v_external_event_id
  for update;

  if found then
    perform logistica_tareas.cancel_active_plan(v_planner_evento_id, v_previous_version);
    v_plan_version := v_previous_version + 1;

    update logistica_tareas.planner_eventos
    set
      nombre = v_nombre_evento,
      novios_id = v_novios_id,
      espacio_evento_id = v_espacio_evento_id,
      fecha_evento = v_fecha_evento,
      semana_operativa_inicio = v_semana_operativa_inicio,
      semana_operativa_fin = v_semana_operativa_fin,
      plan_version = v_plan_version,
      estado_planificacion = 'borrador',
      ruptura_inventario = false,
      last_payload = p_payload,
      updated_at = timezone('utc', now())
    where id = v_planner_evento_id;
  else
    v_plan_version := 1;

    insert into logistica_tareas.planner_eventos (
      external_event_id,
      nombre,
      novios_id,
      espacio_evento_id,
      fecha_evento,
      semana_operativa_inicio,
      semana_operativa_fin,
      plan_version,
      estado_planificacion,
      ruptura_inventario,
      last_payload
    )
    values (
      v_external_event_id,
      v_nombre_evento,
      v_novios_id,
      v_espacio_evento_id,
      v_fecha_evento,
      v_semana_operativa_inicio,
      v_semana_operativa_fin,
      v_plan_version,
      'borrador',
      false,
      p_payload
    )
    returning id into v_planner_evento_id;
  end if;

  for v_linea in
    select value
    from jsonb_array_elements(v_lineas)
  loop
    v_external_line_id := nullif(trim(v_linea ->> 'external_line_id'), '');
    v_requeridos_iniciales := nullif(trim(v_linea ->> 'cantidad'), '')::integer;

    if v_external_line_id is null then
      raise exception 'Cada linea debe incluir external_line_id';
    end if;

    if v_requeridos_iniciales is null or v_requeridos_iniciales <= 0 then
      raise exception 'La linea % debe incluir una cantidad positiva', v_external_line_id;
    end if;

    v_articulo_id := logistica_tareas.resolve_articulo_ref(coalesce(v_linea ->> 'articulo_ref', v_linea ->> 'articulo_id'));

    select ceil(v_requeridos_iniciales * (1 + coeficiente))::integer
    into v_requeridos_finales
    from logistica_tareas.articulos
    where id = v_articulo_id;

    insert into logistica_tareas.planner_lineas (
      planner_evento_id,
      plan_version,
      external_line_id,
      articulo_id,
      requeridos_iniciales,
      requeridos_finales
    )
    values (
      v_planner_evento_id,
      v_plan_version,
      v_external_line_id,
      v_articulo_id,
      v_requeridos_iniciales,
      greatest(v_requeridos_finales, 1)
    )
    returning id into v_linea_id;

    if exists (
      select 1
      from logistica_tareas.articulo_componentes
      where articulo_paquete_id = v_articulo_id
    ) then
      insert into logistica_tareas.planner_requerimientos (
        planner_evento_id,
        plan_version,
        planner_linea_id,
        articulo_solicitado_id,
        articulo_id,
        cantidad_requerida
      )
      select
        v_planner_evento_id,
        v_plan_version,
        v_linea_id,
        v_articulo_id,
        componente.articulo_componente_id,
        greatest(v_requeridos_finales, 1) * componente.cantidad_componente
      from logistica_tareas.articulo_componentes componente
      where componente.articulo_paquete_id = v_articulo_id;
    else
      insert into logistica_tareas.planner_requerimientos (
        planner_evento_id,
        plan_version,
        planner_linea_id,
        articulo_solicitado_id,
        articulo_id,
        cantidad_requerida
      )
      values (
        v_planner_evento_id,
        v_plan_version,
        v_linea_id,
        v_articulo_id,
        v_articulo_id,
        greatest(v_requeridos_finales, 1)
      );
    end if;
  end loop;

  for v_requerimiento in
    select *
    from logistica_tareas.planner_requerimientos
    where planner_evento_id = v_planner_evento_id
      and plan_version = v_plan_version
    order by id
  loop
    perform logistica_tareas.ensure_inventory_row(v_espacio_evento_id, v_requerimiento.articulo_id);
    perform logistica_tareas.ensure_inventory_row(v_cp_id, v_requerimiento.articulo_id);

    select espacio_fuente_id
    into v_fuente_1_id
    from logistica_tareas.prioridades_abastecimiento
    where espacio_evento_id = v_espacio_evento_id
      and prioridad = 1;

    select espacio_fuente_id
    into v_fuente_2_id
    from logistica_tareas.prioridades_abastecimiento
    where espacio_evento_id = v_espacio_evento_id
      and prioridad = 2;

    if v_fuente_1_id is not null then
      perform logistica_tareas.ensure_inventory_row(v_fuente_1_id, v_requerimiento.articulo_id);
    end if;

    if v_fuente_2_id is not null then
      perform logistica_tareas.ensure_inventory_row(v_fuente_2_id, v_requerimiento.articulo_id);
    end if;

    for v_prioridad in
      select id
      from logistica_tareas.inventario
      where articulo_id = v_requerimiento.articulo_id
        and espacio_id in (
          v_espacio_evento_id,
          v_cp_id,
          coalesce(v_fuente_1_id, -1),
          coalesce(v_fuente_2_id, -1)
        )
      order by espacio_id
      for update
    loop
      null;
    end loop;

    v_detalle := '[]'::jsonb;
    v_local_disponible := logistica_tareas.available_quantity(v_espacio_evento_id, v_requerimiento.articulo_id, v_semana_operativa_inicio);
    v_reserva_local := least(v_requerimiento.cantidad_requerida, v_local_disponible);

    if v_reserva_local > 0 then
      insert into logistica_tareas.inventario_movimientos (
        planner_evento_id,
        plan_version,
        planner_requerimiento_id,
        semana_operativa_inicio,
        tipo,
        estado,
        espacio_origen_id,
        espacio_destino_id,
        articulo_id,
        cantidad
      )
      values (
        v_planner_evento_id,
        v_plan_version,
        v_requerimiento.id,
        v_semana_operativa_inicio,
        'reserva_local',
        'activo',
        v_espacio_evento_id,
        null,
        v_requerimiento.articulo_id,
        v_reserva_local
      );

      v_detalle := v_detalle || jsonb_build_array(
        jsonb_build_object(
          'tipo', 'reserva_local',
          'espacio_origen_id', v_espacio_evento_id,
          'cantidad', v_reserva_local
        )
      );
    end if;

    v_faltante := v_requerimiento.cantidad_requerida - v_reserva_local;
    v_asignado_externo := 0;

    if v_faltante > 0 then
      v_cp_disponible := logistica_tareas.available_quantity(v_cp_id, v_requerimiento.articulo_id, v_semana_operativa_inicio);
      v_fuente_1_disponible := coalesce(logistica_tareas.available_quantity(v_fuente_1_id, v_requerimiento.articulo_id, v_semana_operativa_inicio), 0);
      v_fuente_2_disponible := coalesce(logistica_tareas.available_quantity(v_fuente_2_id, v_requerimiento.articulo_id, v_semana_operativa_inicio), 0);

      if v_cp_disponible >= v_faltante then
        perform logistica_tareas.create_transfer_task(
          v_planner_evento_id,
          v_plan_version,
          v_requerimiento.id,
          v_semana_operativa_inicio,
          v_cp_id,
          v_espacio_evento_id,
          v_requerimiento.articulo_id,
          v_faltante
        );
        v_asignado_externo := v_faltante;
        v_detalle := v_detalle || jsonb_build_array(
          jsonb_build_object(
            'tipo', 'reserva_traslado',
            'espacio_origen_id', v_cp_id,
            'espacio_destino_id', v_espacio_evento_id,
            'cantidad', v_faltante
          )
        );
      elsif v_fuente_1_id is not null and v_fuente_1_disponible >= v_faltante then
        perform logistica_tareas.create_transfer_task(
          v_planner_evento_id,
          v_plan_version,
          v_requerimiento.id,
          v_semana_operativa_inicio,
          v_fuente_1_id,
          v_espacio_evento_id,
          v_requerimiento.articulo_id,
          v_faltante
        );
        v_asignado_externo := v_faltante;
        v_detalle := v_detalle || jsonb_build_array(
          jsonb_build_object(
            'tipo', 'reserva_traslado',
            'espacio_origen_id', v_fuente_1_id,
            'espacio_destino_id', v_espacio_evento_id,
            'cantidad', v_faltante
          )
        );
      elsif v_fuente_2_id is not null and v_fuente_2_disponible >= v_faltante then
        perform logistica_tareas.create_transfer_task(
          v_planner_evento_id,
          v_plan_version,
          v_requerimiento.id,
          v_semana_operativa_inicio,
          v_fuente_2_id,
          v_espacio_evento_id,
          v_requerimiento.articulo_id,
          v_faltante
        );
        v_asignado_externo := v_faltante;
        v_detalle := v_detalle || jsonb_build_array(
          jsonb_build_object(
            'tipo', 'reserva_traslado',
            'espacio_origen_id', v_fuente_2_id,
            'espacio_destino_id', v_espacio_evento_id,
            'cantidad', v_faltante
          )
        );
      else
        v_total_disponible := coalesce(v_cp_disponible, 0) + coalesce(v_fuente_1_disponible, 0) + coalesce(v_fuente_2_disponible, 0);

        if v_total_disponible >= v_faltante then
          v_asignar := least(coalesce(v_cp_disponible, 0), v_faltante);
          if v_asignar > 0 then
            perform logistica_tareas.create_transfer_task(
              v_planner_evento_id,
              v_plan_version,
              v_requerimiento.id,
              v_semana_operativa_inicio,
              v_cp_id,
              v_espacio_evento_id,
              v_requerimiento.articulo_id,
              v_asignar
            );
            v_asignado_externo := v_asignado_externo + v_asignar;
            v_detalle := v_detalle || jsonb_build_array(
              jsonb_build_object(
                'tipo', 'reserva_traslado',
                'espacio_origen_id', v_cp_id,
                'espacio_destino_id', v_espacio_evento_id,
                'cantidad', v_asignar
              )
            );
          end if;

          v_asignar := least(coalesce(v_fuente_1_disponible, 0), v_faltante - v_asignado_externo);
          if v_asignar > 0 then
            perform logistica_tareas.create_transfer_task(
              v_planner_evento_id,
              v_plan_version,
              v_requerimiento.id,
              v_semana_operativa_inicio,
              v_fuente_1_id,
              v_espacio_evento_id,
              v_requerimiento.articulo_id,
              v_asignar
            );
            v_asignado_externo := v_asignado_externo + v_asignar;
            v_detalle := v_detalle || jsonb_build_array(
              jsonb_build_object(
                'tipo', 'reserva_traslado',
                'espacio_origen_id', v_fuente_1_id,
                'espacio_destino_id', v_espacio_evento_id,
                'cantidad', v_asignar
              )
            );
          end if;

          v_asignar := least(coalesce(v_fuente_2_disponible, 0), v_faltante - v_asignado_externo);
          if v_asignar > 0 then
            perform logistica_tareas.create_transfer_task(
              v_planner_evento_id,
              v_plan_version,
              v_requerimiento.id,
              v_semana_operativa_inicio,
              v_fuente_2_id,
              v_espacio_evento_id,
              v_requerimiento.articulo_id,
              v_asignar
            );
            v_asignado_externo := v_asignado_externo + v_asignar;
            v_detalle := v_detalle || jsonb_build_array(
              jsonb_build_object(
                'tipo', 'reserva_traslado',
                'espacio_origen_id', v_fuente_2_id,
                'espacio_destino_id', v_espacio_evento_id,
                'cantidad', v_asignar
              )
            );
          end if;
        end if;
      end if;
    end if;

    update logistica_tareas.planner_requerimientos
    set
      cantidad_reservada_local = v_reserva_local,
      cantidad_asignada_externa = v_asignado_externo,
      cantidad_en_ruptura = greatest(v_requerimiento.cantidad_requerida - v_reserva_local - v_asignado_externo, 0),
      estado_cobertura = case
        when (v_requerimiento.cantidad_requerida - v_reserva_local - v_asignado_externo) > 0
          then 'ruptura'::logistica_tareas.requerimiento_estado
        else 'cubierto'::logistica_tareas.requerimiento_estado
      end,
      detalle_cobertura = v_detalle
    where id = v_requerimiento.id;

    if (v_requerimiento.cantidad_requerida - v_reserva_local - v_asignado_externo) > 0 then
      v_tiene_ruptura := true;
    end if;
  end loop;

  update logistica_tareas.planner_eventos
  set
    estado_planificacion = case
      when v_tiene_ruptura then 'ruptura'::logistica_tareas.planner_estado
      else 'planificado'::logistica_tareas.planner_estado
    end,
    ruptura_inventario = v_tiene_ruptura,
    updated_at = timezone('utc', now())
  where id = v_planner_evento_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'planner_requerimiento_id', pr.id,
        'planner_linea_id', pr.planner_linea_id,
        'articulo_id', pr.articulo_id,
        'articulo_nombre', a.nombre,
        'articulo_solicitado_id', pr.articulo_solicitado_id,
        'cantidad_requerida', pr.cantidad_requerida,
        'cantidad_reservada_local', pr.cantidad_reservada_local,
        'cantidad_asignada_externa', pr.cantidad_asignada_externa,
        'cantidad_en_ruptura', pr.cantidad_en_ruptura,
        'estado_cobertura', pr.estado_cobertura,
        'detalle_cobertura', pr.detalle_cobertura
      )
      order by pr.id
    ),
    '[]'::jsonb
  )
  into v_requirements
  from logistica_tareas.planner_requerimientos pr
  join logistica_tareas.articulos a on a.id = pr.articulo_id
  where pr.planner_evento_id = v_planner_evento_id
    and pr.plan_version = v_plan_version;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'tarea_id', t.id,
        'articulo_id', t.articulo_id,
        'articulo_nombre', a.nombre,
        'cantidad', t.cantidad,
        'estado', t.estado,
        'remitente_espacio_id', t.remitente_espacio_id,
        'remitente_codigo', origen.codigo,
        'receptor_espacio_id', t.receptor_espacio_id,
        'receptor_codigo', destino.codigo
      )
      order by t.id
    ),
    '[]'::jsonb
  )
  into v_tasks
  from logistica_tareas.tareas t
  join logistica_tareas.articulos a on a.id = t.articulo_id
  join logistica_tareas.espacios origen on origen.id = t.remitente_espacio_id
  join logistica_tareas.espacios destino on destino.id = t.receptor_espacio_id
  where t.planner_evento_id = v_planner_evento_id
    and t.plan_version = v_plan_version;

  return jsonb_build_object(
    'planner_evento_id', v_planner_evento_id,
    'plan_version', v_plan_version,
    'semana_operativa_inicio', v_semana_operativa_inicio,
    'semana_operativa_fin', v_semana_operativa_fin,
    'estado_planificacion', case when v_tiene_ruptura then 'ruptura' else 'planificado' end,
    'ruptura_inventario', v_tiene_ruptura,
    'tareas_creadas', jsonb_array_length(v_tasks),
    'tareas', v_tasks,
    'requerimientos', v_requirements
  );
end;
$function$;
create or replace function logistica_tareas.complete_task(
  p_tarea_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
declare
  v_tarea logistica_tareas.tareas%rowtype;
  v_movimiento logistica_tareas.inventario_movimientos%rowtype;
  v_stock_origen integer;
begin
  select *
  into v_tarea
  from logistica_tareas.tareas
  where id = p_tarea_id
  for update;

  if not found then
    raise exception 'No existe la tarea %', p_tarea_id;
  end if;

  if v_tarea.estado = 'completada'::logistica_tareas.tarea_estado then
    raise exception 'La tarea % ya esta completada', p_tarea_id;
  end if;

  if v_tarea.estado = 'cancelada'::logistica_tareas.tarea_estado then
    raise exception 'La tarea % esta cancelada', p_tarea_id;
  end if;

  select *
  into v_movimiento
  from logistica_tareas.inventario_movimientos
  where tarea_id = p_tarea_id
    and estado = 'activo'::logistica_tareas.movimiento_estado
  order by id desc
  limit 1
  for update;

  if not found then
    raise exception 'La tarea % no tiene una reserva de traslado activa', p_tarea_id;
  end if;

  perform logistica_tareas.ensure_inventory_row(v_tarea.remitente_espacio_id, v_tarea.articulo_id);
  perform logistica_tareas.ensure_inventory_row(v_tarea.receptor_espacio_id, v_tarea.articulo_id);

  select cantidad
  into v_stock_origen
  from logistica_tareas.inventario
  where espacio_id = v_tarea.remitente_espacio_id
    and articulo_id = v_tarea.articulo_id
  for update;

  perform 1
  from logistica_tareas.inventario
  where espacio_id = v_tarea.receptor_espacio_id
    and articulo_id = v_tarea.articulo_id
  for update;

  if v_stock_origen < v_tarea.cantidad then
    raise exception 'Inventario insuficiente para completar la tarea %', p_tarea_id;
  end if;

  update logistica_tareas.inventario
  set cantidad = cantidad - v_tarea.cantidad
  where espacio_id = v_tarea.remitente_espacio_id
    and articulo_id = v_tarea.articulo_id;

  update logistica_tareas.inventario
  set cantidad = cantidad + v_tarea.cantidad
  where espacio_id = v_tarea.receptor_espacio_id
    and articulo_id = v_tarea.articulo_id;

  update logistica_tareas.tareas
  set
    estado = 'completada',
    completed_at = timezone('utc', now()),
    updated_at = timezone('utc', now())
  where id = p_tarea_id;

  update logistica_tareas.inventario_movimientos
  set
    estado = 'aplicado',
    applied_at = timezone('utc', now()),
    updated_at = timezone('utc', now())
  where id = v_movimiento.id;

  insert into logistica_tareas.inventario_movimientos (
    planner_evento_id,
    plan_version,
    planner_requerimiento_id,
    tarea_id,
    semana_operativa_inicio,
    tipo,
    estado,
    espacio_origen_id,
    espacio_destino_id,
    articulo_id,
    cantidad,
    applied_at
  )
  values (
    v_tarea.planner_evento_id,
    v_tarea.plan_version,
    v_tarea.planner_requerimiento_id,
    v_tarea.id,
    v_movimiento.semana_operativa_inicio,
    'traslado_completado',
    'aplicado',
    v_tarea.remitente_espacio_id,
    v_tarea.receptor_espacio_id,
    v_tarea.articulo_id,
    v_tarea.cantidad,
    timezone('utc', now())
  );

  return jsonb_build_object(
    'tarea_id', v_tarea.id,
    'estado', 'completada',
    'articulo_id', v_tarea.articulo_id,
    'cantidad', v_tarea.cantidad,
    'remitente_espacio_id', v_tarea.remitente_espacio_id,
    'receptor_espacio_id', v_tarea.receptor_espacio_id
  );
end;
$function$;
grant usage on schema logistica_tareas to service_role;
grant execute on function logistica_tareas.sync_planner_event(jsonb) to service_role;
grant execute on function logistica_tareas.complete_task(bigint) to service_role;
