do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'logistica_tareas'
      and t.typname = 'conteo_inventario_estado'
  ) then
    create type logistica_tareas.conteo_inventario_estado as enum (
      'pendiente',
      'aprobado',
      'rechazado'
    );
  end if;
end;
$$;
create table if not exists logistica_tareas.conteos_inventario_pendientes (
  id bigint generated by default as identity primary key,
  espacio_id bigint not null references logistica_tareas.espacios (id) on delete cascade,
  articulo_id bigint not null references logistica_tareas.articulos (id) on delete cascade,
  actor_nombre text not null,
  estado logistica_tareas.conteo_inventario_estado not null default 'pendiente',
  cantidad_teorica integer not null default 0 check (cantidad_teorica >= 0),
  cantidad_real integer not null check (cantidad_real >= 0),
  diferencia integer not null,
  reviewed_by_nombre text,
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint conteos_inventario_pendientes_actor_check check (length(trim(actor_nombre)) > 0),
  constraint conteos_inventario_pendientes_diferencia_check check (
    diferencia = (cantidad_real - cantidad_teorica)
    and diferencia <> 0
  ),
  constraint conteos_inventario_pendientes_unique unique (espacio_id, articulo_id, actor_nombre)
);
create index if not exists conteos_inventario_pendientes_actor_espacio_idx
  on logistica_tareas.conteos_inventario_pendientes (actor_nombre, espacio_id, estado);
drop trigger if exists tr_conteos_inventario_pendientes_touch_updated_at on logistica_tareas.conteos_inventario_pendientes;
create trigger tr_conteos_inventario_pendientes_touch_updated_at
before update on logistica_tareas.conteos_inventario_pendientes
for each row execute function logistica_tareas.touch_updated_at();
create or replace function logistica_tareas.list_inventory_spaces()
returns table (
  espacio_id bigint,
  espacio_codigo text,
  espacio_nombre text,
  espacio_rol logistica_tareas.espacio_rol
)
language sql
stable
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
  select
    e.id as espacio_id,
    e.codigo as espacio_codigo,
    e.nombre as espacio_nombre,
    e.rol as espacio_rol
  from logistica_tareas.espacios e
  order by
    case when e.rol = 'almacen'::logistica_tareas.espacio_rol then 0 else 1 end,
    coalesce(e.codigo, e.nombre),
    e.id;
$function$;
create or replace function logistica_tareas.list_space_inventory_rows(
  p_espacio_id bigint,
  p_actor_nombre text,
  p_formulario text default null
)
returns table (
  articulo_id bigint,
  articulo_nombre text,
  tipologia text,
  formulario text,
  subgrupo text,
  cantidad_teorica integer,
  cantidad_real integer,
  diferencia integer,
  conteo_estado logistica_tareas.conteo_inventario_estado,
  conteo_updated_at timestamptz
)
language sql
stable
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
  with actor as (
    select nullif(trim(coalesce(p_actor_nombre, '')), '') as actor_nombre
  )
  select
    a.id as articulo_id,
    a.nombre as articulo_nombre,
    a.tipologia,
    a.formulario,
    a.subgrupo,
    coalesce(i.cantidad, 0)::integer as cantidad_teorica,
    coalesce(cp.cantidad_real, coalesce(i.cantidad, 0))::integer as cantidad_real,
    coalesce(cp.diferencia, 0)::integer as diferencia,
    cp.estado as conteo_estado,
    cp.updated_at as conteo_updated_at
  from logistica_tareas.articulos a
  left join logistica_tareas.inventario i
    on i.articulo_id = a.id
   and i.espacio_id = p_espacio_id
  left join actor act on true
  left join logistica_tareas.conteos_inventario_pendientes cp
    on cp.articulo_id = a.id
   and cp.espacio_id = p_espacio_id
   and cp.actor_nombre = act.actor_nombre
   and cp.estado = 'pendiente'::logistica_tareas.conteo_inventario_estado
  where p_espacio_id is not null
    and (
      nullif(trim(coalesce(p_formulario, '')), '') is null
      or a.formulario = nullif(trim(coalesce(p_formulario, '')), '')
    )
  order by
    coalesce(a.subgrupo, '(Sin subgrupo)'),
    a.nombre,
    a.id;
$function$;
create or replace function logistica_tareas.submit_space_inventory_count(
  p_espacio_id bigint,
  p_actor_nombre text,
  p_differences jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'logistica_tareas', 'public'
as $function$
declare
  v_actor_nombre text := nullif(trim(coalesce(p_actor_nombre, '')), '');
  v_payload jsonb := coalesce(p_differences, '[]'::jsonb);
  v_active_rows integer := 0;
  v_total_payload_rows integer := 0;
begin
  if p_espacio_id is null then
    raise exception 'espacio_id es obligatorio';
  end if;

  if v_actor_nombre is null then
    raise exception 'actor_nombre es obligatorio';
  end if;

  perform 1
  from logistica_tareas.espacios
  where id = p_espacio_id;

  if not found then
    raise exception 'No existe el espacio %', p_espacio_id;
  end if;

  if jsonb_typeof(v_payload) <> 'array' then
    raise exception 'p_differences debe ser un arreglo JSON';
  end if;

  create temporary table _inventory_count_input (
    articulo_id bigint not null,
    cantidad_real integer not null
  ) on commit drop;

  insert into _inventory_count_input (articulo_id, cantidad_real)
  select
    (item ->> 'articulo_id')::bigint,
    (item ->> 'cantidad_real')::integer
  from jsonb_array_elements(v_payload) as item;

  get diagnostics v_total_payload_rows = row_count;

  if exists (
    select 1
    from _inventory_count_input
    where articulo_id is null
      or cantidad_real is null
      or cantidad_real < 0
  ) then
    raise exception 'Cada diferencia debe incluir articulo_id y cantidad_real >= 0';
  end if;

  if exists (
    select 1
    from (
      select articulo_id
      from _inventory_count_input
      group by articulo_id
      having count(*) > 1
    ) duplicated
  ) then
    raise exception 'No se permiten articulo_id duplicados en el envio';
  end if;

  if exists (
    select 1
    from _inventory_count_input input
    left join logistica_tareas.articulos a on a.id = input.articulo_id
    where a.id is null
  ) then
    raise exception 'El envio incluye articulos inexistentes';
  end if;

  create temporary table _inventory_count_normalized (
    articulo_id bigint primary key,
    cantidad_teorica integer not null,
    cantidad_real integer not null,
    diferencia integer not null
  ) on commit drop;

  insert into _inventory_count_normalized (
    articulo_id,
    cantidad_teorica,
    cantidad_real,
    diferencia
  )
  select
    input.articulo_id,
    coalesce(i.cantidad, 0)::integer as cantidad_teorica,
    input.cantidad_real,
    (input.cantidad_real - coalesce(i.cantidad, 0))::integer as diferencia
  from _inventory_count_input input
  left join logistica_tareas.inventario i
    on i.espacio_id = p_espacio_id
   and i.articulo_id = input.articulo_id
  where input.cantidad_real <> coalesce(i.cantidad, 0);

  insert into logistica_tareas.conteos_inventario_pendientes (
    espacio_id,
    articulo_id,
    actor_nombre,
    estado,
    cantidad_teorica,
    cantidad_real,
    diferencia,
    reviewed_by_nombre,
    reviewed_at
  )
  select
    p_espacio_id,
    normalized.articulo_id,
    v_actor_nombre,
    'pendiente'::logistica_tareas.conteo_inventario_estado,
    normalized.cantidad_teorica,
    normalized.cantidad_real,
    normalized.diferencia,
    null,
    null
  from _inventory_count_normalized normalized
  on conflict (espacio_id, articulo_id, actor_nombre)
  do update
  set
    estado = 'pendiente'::logistica_tareas.conteo_inventario_estado,
    cantidad_teorica = excluded.cantidad_teorica,
    cantidad_real = excluded.cantidad_real,
    diferencia = excluded.diferencia,
    reviewed_by_nombre = null,
    reviewed_at = null,
    updated_at = timezone('utc', now());

  delete from logistica_tareas.conteos_inventario_pendientes pending
  where pending.espacio_id = p_espacio_id
    and pending.actor_nombre = v_actor_nombre
    and pending.estado = 'pendiente'::logistica_tareas.conteo_inventario_estado
    and not exists (
      select 1
      from _inventory_count_normalized normalized
      where normalized.articulo_id = pending.articulo_id
    );

  select count(*)
  into v_active_rows
  from logistica_tareas.conteos_inventario_pendientes pending
  where pending.espacio_id = p_espacio_id
    and pending.actor_nombre = v_actor_nombre
    and pending.estado = 'pendiente'::logistica_tareas.conteo_inventario_estado;

  return jsonb_build_object(
    'espacio_id', p_espacio_id,
    'actor_nombre', v_actor_nombre,
    'payload_rows', v_total_payload_rows,
    'differences_saved', (select count(*) from _inventory_count_normalized),
    'pending_rows', v_active_rows
  );
end;
$function$;
grant execute on function logistica_tareas.list_inventory_spaces() to anon, authenticated;
grant execute on function logistica_tareas.list_space_inventory_rows(bigint, text, text) to anon, authenticated;
grant execute on function logistica_tareas.submit_space_inventory_count(bigint, text, jsonb) to anon, authenticated;
grant execute on function logistica_tareas.list_inventory_spaces() to service_role;
grant execute on function logistica_tareas.list_space_inventory_rows(bigint, text, text) to service_role;
grant execute on function logistica_tareas.submit_space_inventory_count(bigint, text, jsonb) to service_role;
